# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Classifica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1040)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icone/Immagini/Icona/iconaApp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 90, 1041, 591))
        self.tableView.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.659773, y1:0.62, x2:0.960227, y2:0.978, stop:0 rgba(0, 0, 185, 248), stop:1 rgba(85, 147, 255, 255));")
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 981, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 850, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 123, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 850, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 215, 0);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 900, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(34, 139, 34);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 900, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(144, 238, 144);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 950, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 140, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 950, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(220, 20, 60);")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1310, 780, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1090, 90, 411, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(0, 123, 255);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: center;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.sky_btn_classifica = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_classifica.setFont(font)
        self.sky_btn_classifica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_classifica.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_classifica.setObjectName("sky_btn_classifica")
        self.verticalLayout.addWidget(self.sky_btn_classifica)
        self.sky_btn_risultati = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_risultati.setFont(font)
        self.sky_btn_risultati.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_risultati.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_risultati.setObjectName("sky_btn_risultati")
        self.verticalLayout.addWidget(self.sky_btn_risultati)
        self.sky_btn_news = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_news.setFont(font)
        self.sky_btn_news.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_news.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_news.setObjectName("sky_btn_news")
        self.verticalLayout.addWidget(self.sky_btn_news)
        self.sky_btn_formazioni = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_formazioni.setFont(font)
        self.sky_btn_formazioni.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_formazioni.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_formazioni.setObjectName("sky_btn_formazioni")
        self.verticalLayout.addWidget(self.sky_btn_formazioni)
        self.sky_btn_squadre = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_squadre.setFont(font)
        self.sky_btn_squadre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_squadre.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_squadre.setObjectName("sky_btn_squadre")
        self.verticalLayout.addWidget(self.sky_btn_squadre)
        self.sky_btn_marcatori = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_marcatori.setFont(font)
        self.sky_btn_marcatori.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_marcatori.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_marcatori.setObjectName("sky_btn_marcatori")
        self.verticalLayout.addWidget(self.sky_btn_marcatori)
        self.sky_btn_programma = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_programma.setFont(font)
        self.sky_btn_programma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_programma.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_programma.setObjectName("sky_btn_programma")
        self.verticalLayout.addWidget(self.sky_btn_programma)
        self.sky_btn_partite = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_partite.setFont(font)
        self.sky_btn_partite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_partite.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_partite.setObjectName("sky_btn_partite")
        self.verticalLayout.addWidget(self.sky_btn_partite)
        self.sky_btn_app = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_app.setFont(font)
        self.sky_btn_app.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_app.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_app.setObjectName("sky_btn_app")
        self.verticalLayout.addWidget(self.sky_btn_app)
        self.sky_btn_highlights = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sky_btn_highlights.setFont(font)
        self.sky_btn_highlights.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sky_btn_highlights.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 123, 255, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(85, 147, 255, 255), stop:1 rgba(0, 123, 255, 255));\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                      stop:0 rgba(0, 100, 200, 255), stop:1 rgba(70, 120, 200, 255));\n"
"}")
        self.sky_btn_highlights.setObjectName("sky_btn_highlights")
        self.verticalLayout.addWidget(self.sky_btn_highlights)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1920, 1040))
        self.frame.setStyleSheet("  background-color: qlineargradient(spread:pad, x1:0.659773, y1:0.62, x2:0.960227, y2:0.978, stop:0 rgba(0, 0, 185, 255), stop:1 rgba(85, 147, 255, 255));\n"
"    border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.tableView.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Classifica campionato di calcio serie A 2026/27"))
        self.label_2.setText(_translate("MainWindow", "Champions League (1°-4° posto)"))
        self.label_3.setText(_translate("MainWindow", "Europa League (5°-6° posto)"))
        self.label_4.setText(_translate("MainWindow", "Conference League (7° posto)"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", "Zona retrocessione (18°-20° posto)"))
        self.pushButton.setToolTip(_translate("MainWindow", "Esci"))
        self.pushButton.setText(_translate("MainWindow", "Esci dalla classifica"))
        self.label_8.setText(_translate("MainWindow", "📺 Sky Sport Serie A"))
        self.sky_btn_classifica.setToolTip(_translate("MainWindow", "Visualizza la classifica Sky"))
        self.sky_btn_classifica.setText(_translate("MainWindow", "🏆 Classifica Serie A"))
        self.sky_btn_risultati.setToolTip(_translate("MainWindow", "Visualizza i risultati delle partite nel browser"))
        self.sky_btn_risultati.setText(_translate("MainWindow", "📊 Risultati e Calendario"))
        self.sky_btn_news.setToolTip(_translate("MainWindow", "Visualizza le ultime notizie nel browser"))
        self.sky_btn_news.setText(_translate("MainWindow", "⚽ News Serie A"))
        self.sky_btn_formazioni.setToolTip(_translate("MainWindow", "Visualizza le formazioni delle squadre"))
        self.sky_btn_formazioni.setText(_translate("MainWindow", "📈 Probabili Formazioni"))
        self.sky_btn_squadre.setToolTip(_translate("MainWindow", "Visualizza immagini delle squdre"))
        self.sky_btn_squadre.setText(_translate("MainWindow", "👥 Squadre"))
        self.sky_btn_marcatori.setToolTip(_translate("MainWindow", "Visualizza la classifica dei marcatori"))
        self.sky_btn_marcatori.setText(_translate("MainWindow", "🥅 Marcatori"))
        self.sky_btn_programma.setToolTip(_translate("MainWindow", "Visualizza tv che trasmettono eventi sportivi"))
        self.sky_btn_programma.setText(_translate("MainWindow", "📺 Programma TV Sky e DAZN"))
        self.sky_btn_partite.setToolTip(_translate("MainWindow", "Visualizza partite su Sky previo abbonamento"))
        self.sky_btn_partite.setText(_translate("MainWindow", "🏟️ Partite su Sky"))
        self.sky_btn_app.setToolTip(_translate("MainWindow", "Invito a scaricare sky Go"))
        self.sky_btn_app.setText(_translate("MainWindow", "📱 App Sky Sport"))
        self.sky_btn_highlights.setToolTip(_translate("MainWindow", "Eventi rilevanti delle varie squadre"))
        self.sky_btn_highlights.setText(_translate("MainWindow", "🎯 Highlights"))
import resource_rc
