# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Esiti.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1040)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 80, 1901, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxCasa = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxCasa.setObjectName("comboBoxCasa")
        self.horizontalLayout.addWidget(self.comboBoxCasa)
        self.comboBoxTrasferta = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxTrasferta.setObjectName("comboBoxTrasferta")
        self.horizontalLayout.addWidget(self.comboBoxTrasferta)
        self.framePartita = QtWidgets.QFrame(Dialog)
        self.framePartita.setGeometry(QtCore.QRect(19, 120, 1861, 71))
        self.framePartita.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.framePartita.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePartita.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePartita.setObjectName("framePartita")
        self.labelSqaudraDiCasa = QtWidgets.QLabel(self.framePartita)
        self.labelSqaudraDiCasa.setGeometry(QtCore.QRect(30, 10, 550, 50))
        self.labelSqaudraDiCasa.setStyleSheet("color: white;\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"")
        self.labelSqaudraDiCasa.setObjectName("labelSqaudraDiCasa")
        self.labelScudettoSquadraDiCasa = QtWidgets.QLabel(self.framePartita)
        self.labelScudettoSquadraDiCasa.setGeometry(QtCore.QRect(610, 10, 50, 50))
        self.labelScudettoSquadraDiCasa.setStyleSheet("color: white;\n"
"font: 8pt \"Segoe UI\";")
        self.labelScudettoSquadraDiCasa.setObjectName("labelScudettoSquadraDiCasa")
        self.labelSquadraInTrasferta = QtWidgets.QLabel(self.framePartita)
        self.labelSquadraInTrasferta.setGeometry(QtCore.QRect(970, 10, 550, 50))
        self.labelSquadraInTrasferta.setStyleSheet("color: white;\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.labelSquadraInTrasferta.setObjectName("labelSquadraInTrasferta")
        self.labelScudettoSquadraInTrasferta = QtWidgets.QLabel(self.framePartita)
        self.labelScudettoSquadraInTrasferta.setGeometry(QtCore.QRect(1550, 10, 50, 50))
        self.labelScudettoSquadraInTrasferta.setStyleSheet("color: white;\n"
"font: 8pt \"Segoe UI\";")
        self.labelScudettoSquadraInTrasferta.setObjectName("labelScudettoSquadraInTrasferta")
        self.frameTestataPrincipale = QtWidgets.QFrame(Dialog)
        self.frameTestataPrincipale.setGeometry(QtCore.QRect(10, 0, 1900, 80))
        self.frameTestataPrincipale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTestataPrincipale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTestataPrincipale.setObjectName("frameTestataPrincipale")
        self.labelTestataPrincipale = QtWidgets.QLabel(self.frameTestataPrincipale)
        self.labelTestataPrincipale.setGeometry(QtCore.QRect(475, 10, 950, 61))
        self.labelTestataPrincipale.setStyleSheet("color: rgb(58, 255, 65);\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"")
        self.labelTestataPrincipale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataPrincipale.setObjectName("labelTestataPrincipale")
        self.frameEsitiRanking = QtWidgets.QFrame(Dialog)
        self.frameEsitiRanking.setGeometry(QtCore.QRect(20, 210, 1861, 561))
        self.frameEsitiRanking.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.frameEsitiRanking.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEsitiRanking.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEsitiRanking.setObjectName("frameEsitiRanking")
        self.labelTestataEsitiDalRanking = QtWidgets.QLabel(self.frameEsitiRanking)
        self.labelTestataEsitiDalRanking.setGeometry(QtCore.QRect(475, 0, 950, 31))
        self.labelTestataEsitiDalRanking.setStyleSheet("color: rgb(58, 255, 65);\n"
"font:  16pt \"Segoe UI Black\";\n"
"")
        self.labelTestataEsitiDalRanking.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataEsitiDalRanking.setObjectName("labelTestataEsitiDalRanking")
        self.line = QtWidgets.QFrame(self.frameEsitiRanking)
        self.line.setGeometry(QtCore.QRect(7, 40, 1841, 20))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.framePredizioni = QtWidgets.QFrame(self.frameEsitiRanking)
        self.framePredizioni.setGeometry(QtCore.QRect(10, 62, 331, 485))
        self.framePredizioni.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni.setObjectName("framePredizioni")
        self.labelPredizioni = QtWidgets.QLabel(self.framePredizioni)
        self.labelPredizioni.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni.setObjectName("labelPredizioni")
        self.frameFormaRecente = QtWidgets.QFrame(self.framePredizioni)
        self.frameFormaRecente.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente.setObjectName("frameFormaRecente")
        self.labelFormaRecente = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecente.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente.setObjectName("labelFormaRecente")
        self.labelFormaRecenteSquadraDiCasa = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecenteSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa.setObjectName("labelFormaRecenteSquadraDiCasa")
        self.labelFormaRecenteSquadraInTrasferta = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecenteSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta.setObjectName("labelFormaRecenteSquadraInTrasferta")
        self.frameUnderOver = QtWidgets.QFrame(self.framePredizioni)
        self.frameUnderOver.setGeometry(QtCore.QRect(10, 267, 321, 131))
        self.frameUnderOver.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver.setObjectName("frameUnderOver")
        self.labelUnderOver = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnderOver.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelUnderOver.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver.setObjectName("labelUnderOver")
        self.labelUnder15 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnder15.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelUnder15.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15.setObjectName("labelUnder15")
        self.labelOver15 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelOver15.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelOver15.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15.setObjectName("labelOver15")
        self.labelUnder25 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnder25.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelUnder25.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder25.setObjectName("labelUnder25")
        self.labelOver25 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelOver25.setGeometry(QtCore.QRect(10, 105, 301, 21))
        self.labelOver25.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver25.setObjectName("labelOver25")
        self.frameProbabilitaEsito = QtWidgets.QFrame(self.framePredizioni)
        self.frameProbabilitaEsito.setGeometry(QtCore.QRect(10, 153, 321, 111))
        self.frameProbabilitaEsito.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito.setObjectName("frameProbabilitaEsito")
        self.labelProbabilitaEsito = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaEsito.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelProbabilitaEsito.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito.setObjectName("labelProbabilitaEsito")
        self.labelProbabilitaVittoria = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaVittoria.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelProbabilitaVittoria.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria.setObjectName("labelProbabilitaVittoria")
        self.labelProbabilitaPareggio = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaPareggio.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelProbabilitaPareggio.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaPareggio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio.setObjectName("labelProbabilitaPareggio")
        self.labelProbabilitaSconfitta = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaSconfitta.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelProbabilitaSconfitta.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaSconfitta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaSconfitta.setObjectName("labelProbabilitaSconfitta")
        self.framePredizioneGoal = QtWidgets.QFrame(self.framePredizioni)
        self.framePredizioneGoal.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.framePredizioneGoal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal.setObjectName("framePredizioneGoal")
        self.labelPredizioneGoal = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelPredizioneGoal.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioneGoal.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal.setObjectName("labelPredizioneGoal")
        self.labelGoalPrevisti = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelGoalPrevisti.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelGoalPrevisti.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti.setObjectName("labelGoalPrevisti")
        self.labelEsitoPrevisto = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelEsitoPrevisto.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelEsitoPrevisto.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto.setObjectName("labelEsitoPrevisto")
        self.labelDoppiaChanceSuggerita = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelDoppiaChanceSuggerita.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelDoppiaChanceSuggerita.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelDoppiaChanceSuggerita.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDoppiaChanceSuggerita.setObjectName("labelDoppiaChanceSuggerita")
        self.frameRanking = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRanking.setGeometry(QtCore.QRect(340, 62, 331, 485))
        self.frameRanking.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRanking.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRanking.setObjectName("frameRanking")
        self.labelPredizioni_2 = QtWidgets.QLabel(self.frameRanking)
        self.labelPredizioni_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_2.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_2.setObjectName("labelPredizioni_2")
        self.frameFormaRecente_2 = QtWidgets.QFrame(self.frameRanking)
        self.frameFormaRecente_2.setGeometry(QtCore.QRect(10, 380, 321, 91))
        self.frameFormaRecente_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_2.setObjectName("frameFormaRecente_2")
        self.labelFormaRecente_2 = QtWidgets.QLabel(self.frameFormaRecente_2)
        self.labelFormaRecente_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_2.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_2.setObjectName("labelFormaRecente_2")
        self.labelFormaRecenteSquadraDiCasa_2 = QtWidgets.QLabel(self.frameFormaRecente_2)
        self.labelFormaRecenteSquadraDiCasa_2.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_2.setObjectName("labelFormaRecenteSquadraDiCasa_2")
        self.labelFormaRecenteSquadraInTrasferta_2 = QtWidgets.QLabel(self.frameFormaRecente_2)
        self.labelFormaRecenteSquadraInTrasferta_2.setGeometry(QtCore.QRect(10, 60, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_2.setObjectName("labelFormaRecenteSquadraInTrasferta_2")
        self.frameUnderOver_2 = QtWidgets.QFrame(self.frameRanking)
        self.frameUnderOver_2.setGeometry(QtCore.QRect(10, 270, 321, 91))
        self.frameUnderOver_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver_2.setObjectName("frameUnderOver_2")
        self.labelUnderOver_2 = QtWidgets.QLabel(self.frameUnderOver_2)
        self.labelUnderOver_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelUnderOver_2.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver_2.setObjectName("labelUnderOver_2")
        self.labelUnder15_2 = QtWidgets.QLabel(self.frameUnderOver_2)
        self.labelUnder15_2.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelUnder15_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15_2.setObjectName("labelUnder15_2")
        self.labelOver15_2 = QtWidgets.QLabel(self.frameUnderOver_2)
        self.labelOver15_2.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelOver15_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_2.setObjectName("labelOver15_2")
        self.frameProbabilitaEsito_2 = QtWidgets.QFrame(self.frameRanking)
        self.frameProbabilitaEsito_2.setGeometry(QtCore.QRect(10, 150, 321, 111))
        self.frameProbabilitaEsito_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito_2.setObjectName("frameProbabilitaEsito_2")
        self.labelProbabilitaEsito_2 = QtWidgets.QLabel(self.frameProbabilitaEsito_2)
        self.labelProbabilitaEsito_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelProbabilitaEsito_2.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito_2.setObjectName("labelProbabilitaEsito_2")
        self.labelProbabilitaVittoria_2 = QtWidgets.QLabel(self.frameProbabilitaEsito_2)
        self.labelProbabilitaVittoria_2.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelProbabilitaVittoria_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_2.setObjectName("labelProbabilitaVittoria_2")
        self.labelProbabilitaPareggio_2 = QtWidgets.QLabel(self.frameProbabilitaEsito_2)
        self.labelProbabilitaPareggio_2.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelProbabilitaPareggio_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaPareggio_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio_2.setObjectName("labelProbabilitaPareggio_2")
        self.framePredizioneGoal_2 = QtWidgets.QFrame(self.frameRanking)
        self.framePredizioneGoal_2.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.framePredizioneGoal_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_2.setObjectName("framePredizioneGoal_2")
        self.labelPredizioneGoal_2 = QtWidgets.QLabel(self.framePredizioneGoal_2)
        self.labelPredizioneGoal_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioneGoal_2.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal_2.setObjectName("labelPredizioneGoal_2")
        self.labelGoalPrevisti_2 = QtWidgets.QLabel(self.framePredizioneGoal_2)
        self.labelGoalPrevisti_2.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelGoalPrevisti_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_2.setObjectName("labelGoalPrevisti_2")
        self.labelEsitoPrevisto_2 = QtWidgets.QLabel(self.framePredizioneGoal_2)
        self.labelEsitoPrevisto_2.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelEsitoPrevisto_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_2.setObjectName("labelEsitoPrevisto_2")
        self.frameRanking_2 = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRanking_2.setGeometry(QtCore.QRect(680, 62, 331, 485))
        self.frameRanking_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRanking_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRanking_2.setObjectName("frameRanking_2")
        self.labelPredizioni_3 = QtWidgets.QLabel(self.frameRanking_2)
        self.labelPredizioni_3.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_3.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_3.setObjectName("labelPredizioni_3")
        self.frameUnderOver_3 = QtWidgets.QFrame(self.frameRanking_2)
        self.frameUnderOver_3.setGeometry(QtCore.QRect(10, 360, 321, 131))
        self.frameUnderOver_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver_3.setObjectName("frameUnderOver_3")
        self.labelUnderOver_3 = QtWidgets.QLabel(self.frameUnderOver_3)
        self.labelUnderOver_3.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelUnderOver_3.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver_3.setObjectName("labelUnderOver_3")
        self.labelUnder15_3 = QtWidgets.QLabel(self.frameUnderOver_3)
        self.labelUnder15_3.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelUnder15_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15_3.setObjectName("labelUnder15_3")
        self.labelOver15_3 = QtWidgets.QLabel(self.frameUnderOver_3)
        self.labelOver15_3.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelOver15_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_3.setObjectName("labelOver15_3")
        self.frameProbabilitaEsito_3 = QtWidgets.QFrame(self.frameRanking_2)
        self.frameProbabilitaEsito_3.setGeometry(QtCore.QRect(10, 190, 321, 111))
        self.frameProbabilitaEsito_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito_3.setObjectName("frameProbabilitaEsito_3")
        self.labelProbabilitaEsito_3 = QtWidgets.QLabel(self.frameProbabilitaEsito_3)
        self.labelProbabilitaEsito_3.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelProbabilitaEsito_3.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito_3.setObjectName("labelProbabilitaEsito_3")
        self.labelProbabilitaVittoria_3 = QtWidgets.QLabel(self.frameProbabilitaEsito_3)
        self.labelProbabilitaVittoria_3.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelProbabilitaVittoria_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_3.setObjectName("labelProbabilitaVittoria_3")
        self.labelProbabilitaPareggio_3 = QtWidgets.QLabel(self.frameProbabilitaEsito_3)
        self.labelProbabilitaPareggio_3.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelProbabilitaPareggio_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaPareggio_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio_3.setObjectName("labelProbabilitaPareggio_3")
        self.framePredizioneGoal_3 = QtWidgets.QFrame(self.frameRanking_2)
        self.framePredizioneGoal_3.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.framePredizioneGoal_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_3.setObjectName("framePredizioneGoal_3")
        self.labelPredizioneGoal_3 = QtWidgets.QLabel(self.framePredizioneGoal_3)
        self.labelPredizioneGoal_3.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioneGoal_3.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal_3.setObjectName("labelPredizioneGoal_3")
        self.labelGoalPrevisti_3 = QtWidgets.QLabel(self.framePredizioneGoal_3)
        self.labelGoalPrevisti_3.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelGoalPrevisti_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_3.setObjectName("labelGoalPrevisti_3")
        self.labelEsitoPrevisto_3 = QtWidgets.QLabel(self.framePredizioneGoal_3)
        self.labelEsitoPrevisto_3.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelEsitoPrevisto_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_3.setObjectName("labelEsitoPrevisto_3")
        self.frameRanking_3 = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRanking_3.setGeometry(QtCore.QRect(1010, 62, 331, 485))
        self.frameRanking_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRanking_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRanking_3.setObjectName("frameRanking_3")
        self.labelPredizioni_4 = QtWidgets.QLabel(self.frameRanking_3)
        self.labelPredizioni_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_4.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_4.setObjectName("labelPredizioni_4")
        self.frameUnderOver_4 = QtWidgets.QFrame(self.frameRanking_3)
        self.frameUnderOver_4.setGeometry(QtCore.QRect(10, 360, 321, 131))
        self.frameUnderOver_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver_4.setObjectName("frameUnderOver_4")
        self.labelUnderOver_4 = QtWidgets.QLabel(self.frameUnderOver_4)
        self.labelUnderOver_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelUnderOver_4.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver_4.setObjectName("labelUnderOver_4")
        self.labelUnder15_4 = QtWidgets.QLabel(self.frameUnderOver_4)
        self.labelUnder15_4.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelUnder15_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15_4.setObjectName("labelUnder15_4")
        self.labelOver15_4 = QtWidgets.QLabel(self.frameUnderOver_4)
        self.labelOver15_4.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelOver15_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_4.setObjectName("labelOver15_4")
        self.frameProbabilitaEsito_4 = QtWidgets.QFrame(self.frameRanking_3)
        self.frameProbabilitaEsito_4.setGeometry(QtCore.QRect(10, 190, 321, 111))
        self.frameProbabilitaEsito_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito_4.setObjectName("frameProbabilitaEsito_4")
        self.labelProbabilitaEsito_4 = QtWidgets.QLabel(self.frameProbabilitaEsito_4)
        self.labelProbabilitaEsito_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelProbabilitaEsito_4.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito_4.setObjectName("labelProbabilitaEsito_4")
        self.labelProbabilitaVittoria_4 = QtWidgets.QLabel(self.frameProbabilitaEsito_4)
        self.labelProbabilitaVittoria_4.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelProbabilitaVittoria_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_4.setObjectName("labelProbabilitaVittoria_4")
        self.labelProbabilitaPareggio_4 = QtWidgets.QLabel(self.frameProbabilitaEsito_4)
        self.labelProbabilitaPareggio_4.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelProbabilitaPareggio_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaPareggio_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio_4.setObjectName("labelProbabilitaPareggio_4")
        self.framePredizioneGoal_4 = QtWidgets.QFrame(self.frameRanking_3)
        self.framePredizioneGoal_4.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.framePredizioneGoal_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_4.setObjectName("framePredizioneGoal_4")
        self.labelPredizioneGoal_4 = QtWidgets.QLabel(self.framePredizioneGoal_4)
        self.labelPredizioneGoal_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioneGoal_4.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal_4.setObjectName("labelPredizioneGoal_4")
        self.labelGoalPrevisti_4 = QtWidgets.QLabel(self.framePredizioneGoal_4)
        self.labelGoalPrevisti_4.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelGoalPrevisti_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_4.setObjectName("labelGoalPrevisti_4")
        self.labelEsitoPrevisto_4 = QtWidgets.QLabel(self.framePredizioneGoal_4)
        self.labelEsitoPrevisto_4.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelEsitoPrevisto_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_4.setObjectName("labelEsitoPrevisto_4")
        self.frameRanking_4 = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRanking_4.setGeometry(QtCore.QRect(1350, 60, 361, 485))
        self.frameRanking_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRanking_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRanking_4.setObjectName("frameRanking_4")
        self.labelPredizioni_5 = QtWidgets.QLabel(self.frameRanking_4)
        self.labelPredizioni_5.setGeometry(QtCore.QRect(20, 10, 321, 21))
        self.labelPredizioni_5.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_5.setObjectName("labelPredizioni_5")
        self.frameUnderOver_5 = QtWidgets.QFrame(self.frameRanking_4)
        self.frameUnderOver_5.setGeometry(QtCore.QRect(10, 310, 341, 171))
        self.frameUnderOver_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver_5.setObjectName("frameUnderOver_5")
        self.labelUnderOver_5 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelUnderOver_5.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.labelUnderOver_5.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver_5.setObjectName("labelUnderOver_5")
        self.labelUnder15_5 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelUnder15_5.setGeometry(QtCore.QRect(10, 40, 321, 21))
        self.labelUnder15_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15_5.setObjectName("labelUnder15_5")
        self.labelOver15_5 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelOver15_5.setGeometry(QtCore.QRect(10, 62, 321, 21))
        self.labelOver15_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_5.setObjectName("labelOver15_5")
        self.labelOver15_6 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelOver15_6.setGeometry(QtCore.QRect(10, 80, 321, 21))
        self.labelOver15_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_6.setObjectName("labelOver15_6")
        self.labelOver15_7 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelOver15_7.setGeometry(QtCore.QRect(10, 100, 321, 21))
        self.labelOver15_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_7.setObjectName("labelOver15_7")
        self.labelOver15_8 = QtWidgets.QLabel(self.frameUnderOver_5)
        self.labelOver15_8.setGeometry(QtCore.QRect(10, 120, 321, 21))
        self.labelOver15_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15_8.setObjectName("labelOver15_8")
        self.frameProbabilitaEsito_5 = QtWidgets.QFrame(self.frameRanking_4)
        self.frameProbabilitaEsito_5.setGeometry(QtCore.QRect(10, 130, 331, 161))
        self.frameProbabilitaEsito_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito_5.setObjectName("frameProbabilitaEsito_5")
        self.labelProbabilitaEsito_5 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaEsito_5.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.labelProbabilitaEsito_5.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito_5.setObjectName("labelProbabilitaEsito_5")
        self.labelProbabilitaVittoria_5 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaVittoria_5.setGeometry(QtCore.QRect(10, 40, 321, 21))
        self.labelProbabilitaVittoria_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_5.setObjectName("labelProbabilitaVittoria_5")
        self.labelProbabilitaPareggio_5 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaPareggio_5.setGeometry(QtCore.QRect(10, 62, 321, 21))
        self.labelProbabilitaPareggio_5.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"\n"
"")
        self.labelProbabilitaPareggio_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio_5.setObjectName("labelProbabilitaPareggio_5")
        self.labelProbabilitaVittoria_6 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaVittoria_6.setGeometry(QtCore.QRect(10, 90, 321, 21))
        self.labelProbabilitaVittoria_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_6.setObjectName("labelProbabilitaVittoria_6")
        self.labelProbabilitaVittoria_7 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaVittoria_7.setGeometry(QtCore.QRect(10, 110, 321, 21))
        self.labelProbabilitaVittoria_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_7.setObjectName("labelProbabilitaVittoria_7")
        self.labelProbabilitaVittoria_8 = QtWidgets.QLabel(self.frameProbabilitaEsito_5)
        self.labelProbabilitaVittoria_8.setGeometry(QtCore.QRect(10, 130, 321, 21))
        self.labelProbabilitaVittoria_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria_8.setObjectName("labelProbabilitaVittoria_8")
        self.framePredizioneGoal_5 = QtWidgets.QFrame(self.frameRanking_4)
        self.framePredizioneGoal_5.setGeometry(QtCore.QRect(10, 39, 331, 81))
        self.framePredizioneGoal_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_5.setObjectName("framePredizioneGoal_5")
        self.labelPredizioneGoal_5 = QtWidgets.QLabel(self.framePredizioneGoal_5)
        self.labelPredizioneGoal_5.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.labelPredizioneGoal_5.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal_5.setObjectName("labelPredizioneGoal_5")
        self.labelGoalPrevisti_5 = QtWidgets.QLabel(self.framePredizioneGoal_5)
        self.labelGoalPrevisti_5.setGeometry(QtCore.QRect(10, 40, 321, 21))
        self.labelGoalPrevisti_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_5.setObjectName("labelGoalPrevisti_5")
        self.labelEsitoPrevisto_5 = QtWidgets.QLabel(self.framePredizioneGoal_5)
        self.labelEsitoPrevisto_5.setGeometry(QtCore.QRect(10, 62, 321, 21))
        self.labelEsitoPrevisto_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_5.setObjectName("labelEsitoPrevisto_5")
        self.frameEsitiRanking_2 = QtWidgets.QFrame(Dialog)
        self.frameEsitiRanking_2.setGeometry(QtCore.QRect(20, 770, 1861, 561))
        self.frameEsitiRanking_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.frameEsitiRanking_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEsitiRanking_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEsitiRanking_2.setObjectName("frameEsitiRanking_2")
        self.labelTestataEsitiDalRanking_2 = QtWidgets.QLabel(self.frameEsitiRanking_2)
        self.labelTestataEsitiDalRanking_2.setGeometry(QtCore.QRect(475, 0, 950, 31))
        self.labelTestataEsitiDalRanking_2.setStyleSheet("color: rgb(58, 255, 65);\n"
"font:  16pt \"Segoe UI Black\";\n"
"")
        self.labelTestataEsitiDalRanking_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataEsitiDalRanking_2.setObjectName("labelTestataEsitiDalRanking_2")
        self.line_2 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.line_2.setGeometry(QtCore.QRect(7, 40, 1841, 20))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.framePredizioni_2 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_2.setGeometry(QtCore.QRect(10, 61, 331, 101))
        self.framePredizioni_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_2.setObjectName("framePredizioni_2")
        self.labelPredizioni_6 = QtWidgets.QLabel(self.framePredizioni_2)
        self.labelPredizioni_6.setGeometry(QtCore.QRect(20, 0, 301, 21))
        self.labelPredizioni_6.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_6.setObjectName("labelPredizioni_6")
        self.frameFormaRecente_3 = QtWidgets.QFrame(self.framePredizioni_2)
        self.frameFormaRecente_3.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_3.setObjectName("frameFormaRecente_3")
        self.labelFormaRecente_3 = QtWidgets.QLabel(self.frameFormaRecente_3)
        self.labelFormaRecente_3.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_3.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_3.setObjectName("labelFormaRecente_3")
        self.labelFormaRecenteSquadraDiCasa_3 = QtWidgets.QLabel(self.frameFormaRecente_3)
        self.labelFormaRecenteSquadraDiCasa_3.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_3.setObjectName("labelFormaRecenteSquadraDiCasa_3")
        self.labelFormaRecenteSquadraInTrasferta_3 = QtWidgets.QLabel(self.frameFormaRecente_3)
        self.labelFormaRecenteSquadraInTrasferta_3.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_3.setObjectName("labelFormaRecenteSquadraInTrasferta_3")
        self.labelGoalPrevisti_14 = QtWidgets.QLabel(self.framePredizioni_2)
        self.labelGoalPrevisti_14.setGeometry(QtCore.QRect(20, 30, 301, 21))
        self.labelGoalPrevisti_14.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_14.setObjectName("labelGoalPrevisti_14")
        self.labelGoalPrevisti_6 = QtWidgets.QLabel(self.framePredizioni_2)
        self.labelGoalPrevisti_6.setGeometry(QtCore.QRect(20, 50, 301, 21))
        self.labelGoalPrevisti_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_6.setObjectName("labelGoalPrevisti_6")
        self.labelEsitoPrevisto_6 = QtWidgets.QLabel(self.framePredizioni_2)
        self.labelEsitoPrevisto_6.setGeometry(QtCore.QRect(20, 70, 301, 21))
        self.labelEsitoPrevisto_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_6.setObjectName("labelEsitoPrevisto_6")
        self.framePredizioni_3 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_3.setGeometry(QtCore.QRect(350, 460, 331, 91))
        self.framePredizioni_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_3.setObjectName("framePredizioni_3")
        self.labelPredizioni_12 = QtWidgets.QLabel(self.framePredizioni_3)
        self.labelPredizioni_12.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_12.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_12.setObjectName("labelPredizioni_12")
        self.frameFormaRecente_6 = QtWidgets.QFrame(self.framePredizioni_3)
        self.frameFormaRecente_6.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_6.setObjectName("frameFormaRecente_6")
        self.labelFormaRecente_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecente_6.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_6.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_6.setObjectName("labelFormaRecente_6")
        self.labelFormaRecenteSquadraDiCasa_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecenteSquadraDiCasa_6.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_6.setObjectName("labelFormaRecenteSquadraDiCasa_6")
        self.labelFormaRecenteSquadraInTrasferta_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecenteSquadraInTrasferta_6.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_6.setObjectName("labelFormaRecenteSquadraInTrasferta_6")
        self.framePredizioneGoal_12 = QtWidgets.QFrame(self.framePredizioni_3)
        self.framePredizioneGoal_12.setGeometry(QtCore.QRect(10, 39, 321, 51))
        self.framePredizioneGoal_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_12.setObjectName("framePredizioneGoal_12")
        self.labelGoalPrevisti_12 = QtWidgets.QLabel(self.framePredizioneGoal_12)
        self.labelGoalPrevisti_12.setGeometry(QtCore.QRect(10, 0, 301, 21))
        self.labelGoalPrevisti_12.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_12.setObjectName("labelGoalPrevisti_12")
        self.labelEsitoPrevisto_12 = QtWidgets.QLabel(self.framePredizioneGoal_12)
        self.labelEsitoPrevisto_12.setGeometry(QtCore.QRect(10, 20, 301, 21))
        self.labelEsitoPrevisto_12.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_12.setObjectName("labelEsitoPrevisto_12")
        self.framePredizioni_4 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_4.setGeometry(QtCore.QRect(10, 170, 331, 91))
        self.framePredizioni_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_4.setObjectName("framePredizioni_4")
        self.labelPredizioni_13 = QtWidgets.QLabel(self.framePredizioni_4)
        self.labelPredizioni_13.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_13.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_13.setObjectName("labelPredizioni_13")
        self.frameFormaRecente_7 = QtWidgets.QFrame(self.framePredizioni_4)
        self.frameFormaRecente_7.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_7.setObjectName("frameFormaRecente_7")
        self.labelFormaRecente_7 = QtWidgets.QLabel(self.frameFormaRecente_7)
        self.labelFormaRecente_7.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_7.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_7.setObjectName("labelFormaRecente_7")
        self.labelFormaRecenteSquadraDiCasa_7 = QtWidgets.QLabel(self.frameFormaRecente_7)
        self.labelFormaRecenteSquadraDiCasa_7.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_7.setObjectName("labelFormaRecenteSquadraDiCasa_7")
        self.labelFormaRecenteSquadraInTrasferta_7 = QtWidgets.QLabel(self.frameFormaRecente_7)
        self.labelFormaRecenteSquadraInTrasferta_7.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_7.setObjectName("labelFormaRecenteSquadraInTrasferta_7")
        self.framePredizioneGoal_13 = QtWidgets.QFrame(self.framePredizioni_4)
        self.framePredizioneGoal_13.setGeometry(QtCore.QRect(10, 39, 321, 51))
        self.framePredizioneGoal_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal_13.setObjectName("framePredizioneGoal_13")
        self.labelGoalPrevisti_13 = QtWidgets.QLabel(self.framePredizioneGoal_13)
        self.labelGoalPrevisti_13.setGeometry(QtCore.QRect(10, 0, 301, 21))
        self.labelGoalPrevisti_13.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_13.setObjectName("labelGoalPrevisti_13")
        self.labelEsitoPrevisto_13 = QtWidgets.QLabel(self.framePredizioneGoal_13)
        self.labelEsitoPrevisto_13.setGeometry(QtCore.QRect(10, 20, 301, 21))
        self.labelEsitoPrevisto_13.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_13.setObjectName("labelEsitoPrevisto_13")
        self.framePredizioni_5 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_5.setGeometry(QtCore.QRect(340, 61, 381, 201))
        self.framePredizioni_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_5.setObjectName("framePredizioni_5")
        self.labelPredizioni_7 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelPredizioni_7.setGeometry(QtCore.QRect(20, 0, 301, 21))
        self.labelPredizioni_7.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_7.setObjectName("labelPredizioni_7")
        self.frameFormaRecente_4 = QtWidgets.QFrame(self.framePredizioni_5)
        self.frameFormaRecente_4.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_4.setObjectName("frameFormaRecente_4")
        self.labelFormaRecente_4 = QtWidgets.QLabel(self.frameFormaRecente_4)
        self.labelFormaRecente_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_4.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_4.setObjectName("labelFormaRecente_4")
        self.labelFormaRecenteSquadraDiCasa_4 = QtWidgets.QLabel(self.frameFormaRecente_4)
        self.labelFormaRecenteSquadraDiCasa_4.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_4.setObjectName("labelFormaRecenteSquadraDiCasa_4")
        self.labelFormaRecenteSquadraInTrasferta_4 = QtWidgets.QLabel(self.frameFormaRecente_4)
        self.labelFormaRecenteSquadraInTrasferta_4.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_4.setObjectName("labelFormaRecenteSquadraInTrasferta_4")
        self.labelGoalPrevisti_15 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelGoalPrevisti_15.setGeometry(QtCore.QRect(20, 30, 341, 21))
        self.labelGoalPrevisti_15.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_15.setObjectName("labelGoalPrevisti_15")
        self.labelGoalPrevisti_7 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelGoalPrevisti_7.setGeometry(QtCore.QRect(20, 50, 341, 21))
        self.labelGoalPrevisti_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_7.setObjectName("labelGoalPrevisti_7")
        self.labelEsitoPrevisto_7 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelEsitoPrevisto_7.setGeometry(QtCore.QRect(20, 70, 341, 21))
        self.labelEsitoPrevisto_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_7.setObjectName("labelEsitoPrevisto_7")
        self.labelEsitoPrevisto_8 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelEsitoPrevisto_8.setGeometry(QtCore.QRect(20, 90, 341, 21))
        self.labelEsitoPrevisto_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_8.setObjectName("labelEsitoPrevisto_8")
        self.labelEsitoPrevisto_9 = QtWidgets.QLabel(self.framePredizioni_5)
        self.labelEsitoPrevisto_9.setGeometry(QtCore.QRect(20, 110, 341, 21))
        self.labelEsitoPrevisto_9.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_9.setObjectName("labelEsitoPrevisto_9")
        self.framePredizioni_6 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_6.setGeometry(QtCore.QRect(720, 61, 561, 201))
        self.framePredizioni_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_6.setObjectName("framePredizioni_6")
        self.labelPredizioni_8 = QtWidgets.QLabel(self.framePredizioni_6)
        self.labelPredizioni_8.setGeometry(QtCore.QRect(20, 0, 301, 21))
        self.labelPredizioni_8.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_8.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_8.setObjectName("labelPredizioni_8")
        self.frameFormaRecente_8 = QtWidgets.QFrame(self.framePredizioni_6)
        self.frameFormaRecente_8.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_8.setObjectName("frameFormaRecente_8")
        self.labelFormaRecente_8 = QtWidgets.QLabel(self.frameFormaRecente_8)
        self.labelFormaRecente_8.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_8.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_8.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_8.setObjectName("labelFormaRecente_8")
        self.labelFormaRecenteSquadraDiCasa_8 = QtWidgets.QLabel(self.frameFormaRecente_8)
        self.labelFormaRecenteSquadraDiCasa_8.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_8.setObjectName("labelFormaRecenteSquadraDiCasa_8")
        self.labelFormaRecenteSquadraInTrasferta_8 = QtWidgets.QLabel(self.frameFormaRecente_8)
        self.labelFormaRecenteSquadraInTrasferta_8.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_8.setObjectName("labelFormaRecenteSquadraInTrasferta_8")
        self.labelGoalPrevisti_16 = QtWidgets.QLabel(self.framePredizioni_6)
        self.labelGoalPrevisti_16.setGeometry(QtCore.QRect(20, 30, 521, 21))
        self.labelGoalPrevisti_16.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_16.setObjectName("labelGoalPrevisti_16")
        self.labelGoalPrevisti_8 = QtWidgets.QLabel(self.framePredizioni_6)
        self.labelGoalPrevisti_8.setGeometry(QtCore.QRect(20, 50, 521, 21))
        self.labelGoalPrevisti_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_8.setObjectName("labelGoalPrevisti_8")
        self.framePredizioni_7 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_7.setGeometry(QtCore.QRect(1280, 60, 381, 201))
        self.framePredizioni_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_7.setObjectName("framePredizioni_7")
        self.labelPredizioni_9 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelPredizioni_9.setGeometry(QtCore.QRect(20, 0, 301, 21))
        self.labelPredizioni_9.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_9.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_9.setObjectName("labelPredizioni_9")
        self.frameFormaRecente_9 = QtWidgets.QFrame(self.framePredizioni_7)
        self.frameFormaRecente_9.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_9.setObjectName("frameFormaRecente_9")
        self.labelFormaRecente_9 = QtWidgets.QLabel(self.frameFormaRecente_9)
        self.labelFormaRecente_9.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_9.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_9.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_9.setObjectName("labelFormaRecente_9")
        self.labelFormaRecenteSquadraDiCasa_9 = QtWidgets.QLabel(self.frameFormaRecente_9)
        self.labelFormaRecenteSquadraDiCasa_9.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_9.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_9.setObjectName("labelFormaRecenteSquadraDiCasa_9")
        self.labelFormaRecenteSquadraInTrasferta_9 = QtWidgets.QLabel(self.frameFormaRecente_9)
        self.labelFormaRecenteSquadraInTrasferta_9.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_9.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_9.setObjectName("labelFormaRecenteSquadraInTrasferta_9")
        self.labelGoalPrevisti_17 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelGoalPrevisti_17.setGeometry(QtCore.QRect(20, 30, 341, 21))
        self.labelGoalPrevisti_17.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_17.setObjectName("labelGoalPrevisti_17")
        self.labelGoalPrevisti_9 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelGoalPrevisti_9.setGeometry(QtCore.QRect(20, 50, 341, 21))
        self.labelGoalPrevisti_9.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti_9.setObjectName("labelGoalPrevisti_9")
        self.labelEsitoPrevisto_10 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelEsitoPrevisto_10.setGeometry(QtCore.QRect(20, 70, 341, 21))
        self.labelEsitoPrevisto_10.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_10.setObjectName("labelEsitoPrevisto_10")
        self.labelEsitoPrevisto_14 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelEsitoPrevisto_14.setGeometry(QtCore.QRect(20, 90, 341, 21))
        self.labelEsitoPrevisto_14.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_14.setObjectName("labelEsitoPrevisto_14")
        self.labelEsitoPrevisto_15 = QtWidgets.QLabel(self.framePredizioni_7)
        self.labelEsitoPrevisto_15.setGeometry(QtCore.QRect(20, 110, 341, 21))
        self.labelEsitoPrevisto_15.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto_15.setObjectName("labelEsitoPrevisto_15")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBoxCasa.setToolTip(_translate("Dialog", "Inserire la squadra di casa per predire il match"))
        self.comboBoxTrasferta.setToolTip(_translate("Dialog", "Inserire la squadra in trasferta per predire il match"))
        self.labelSqaudraDiCasa.setText(_translate("Dialog", "Sqaudra di casa"))
        self.labelScudettoSquadraDiCasa.setText(_translate("Dialog", "scudeto"))
        self.labelSquadraInTrasferta.setText(_translate("Dialog", "Sqaudra in trasferta"))
        self.labelScudettoSquadraInTrasferta.setText(_translate("Dialog", "Scudetto"))
        self.labelTestataPrincipale.setText(_translate("Dialog", "=== ANALISI PARTITA ==="))
        self.labelTestataEsitiDalRanking.setText(_translate("Dialog", "=== Esiti Dal Ranking ==="))
        self.labelPredizioni.setText(_translate("Dialog", "PREDIZIONI"))
        self.labelFormaRecente.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelUnderOver.setText(_translate("Dialog", "--- UNDER/OVER ---"))
        self.labelUnder15.setText(_translate("Dialog", "Under 1.5: 43%"))
        self.labelOver15.setText(_translate("Dialog", "Over 1.5: 57%"))
        self.labelUnder25.setText(_translate("Dialog", "Under 2.5: 60%"))
        self.labelOver25.setText(_translate("Dialog", "Over 2.5: 40%"))
        self.labelProbabilitaEsito.setText(_translate("Dialog", "--- Probabilità Esito ---"))
        self.labelProbabilitaVittoria.setText(_translate("Dialog", "1 (Vittoria Roma): 85%"))
        self.labelProbabilitaPareggio.setText(_translate("Dialog", "X (Pareggio): 10%"))
        self.labelProbabilitaSconfitta.setText(_translate("Dialog", "2 (Vittoria Udinese): 15%"))
        self.labelPredizioneGoal.setText(_translate("Dialog", "--- Predizione goals ---"))
        self.labelGoalPrevisti.setText(_translate("Dialog", "Goal previsti: Hellas Verona 1.0 - 1.3 Cremonese"))
        self.labelEsitoPrevisto.setText(_translate("Dialog", "Esito Previsto: 1"))
        self.labelDoppiaChanceSuggerita.setText(_translate("Dialog", "Doppia chance suggerita: 1X"))
        self.labelPredizioni_2.setText(_translate("Dialog", "Ranking Campionati Precedenti"))
        self.labelFormaRecente_2.setText(_translate("Dialog", "📈 --- Statistiche storiche Aggegate ---"))
        self.labelFormaRecenteSquadraDiCasa_2.setText(_translate("Dialog", "Roma: 228 partite, 113-51-64, 375-271"))
        self.labelFormaRecenteSquadraInTrasferta_2.setText(_translate("Dialog", "Udinese: 228 partite, 62-73-93, 265-324"))
        self.labelUnderOver_2.setText(_translate("Dialog", "✈️ --- In Trasferta ---"))
        self.labelUnder15_2.setText(_translate("Dialog", "Roma: 7° posto"))
        self.labelOver15_2.setText(_translate("Dialog", "Udinese: 10° posto"))
        self.labelProbabilitaEsito_2.setText(_translate("Dialog", "🏠 --- In Casa ---"))
        self.labelProbabilitaVittoria_2.setText(_translate("Dialog", "Roma: 3° posto"))
        self.labelProbabilitaPareggio_2.setText(_translate("Dialog", "Udinese: 12° posto%"))
        self.labelPredizioneGoal_2.setText(_translate("Dialog", "📊 --- Generale ---"))
        self.labelGoalPrevisti_2.setText(_translate("Dialog", "Roma 7° posto"))
        self.labelEsitoPrevisto_2.setText(_translate("Dialog", "Udinese 11° posto"))
        self.labelPredizioni_3.setText(_translate("Dialog", "Ranking Campionato Attuale"))
        self.labelUnderOver_3.setText(_translate("Dialog", "✈️ --- In Trasferta ---"))
        self.labelUnder15_3.setText(_translate("Dialog", "Roma: 1° posto"))
        self.labelOver15_3.setText(_translate("Dialog", "Udinese: 9° posto"))
        self.labelProbabilitaEsito_3.setText(_translate("Dialog", "🏠 --- In Casa ---"))
        self.labelProbabilitaVittoria_3.setText(_translate("Dialog", "Roma: 8° posto"))
        self.labelProbabilitaPareggio_3.setText(_translate("Dialog", "Udinese: 9° posto"))
        self.labelPredizioneGoal_3.setText(_translate("Dialog", "📊 --- Generale ---"))
        self.labelGoalPrevisti_3.setText(_translate("Dialog", "Roma: 4° posto"))
        self.labelEsitoPrevisto_3.setText(_translate("Dialog", "Udinese: 9° posto"))
        self.labelPredizioni_4.setText(_translate("Dialog", "Ranking Ultime 5 Partite"))
        self.labelUnderOver_4.setText(_translate("Dialog", "✈️ --- In Trasferta ---"))
        self.labelUnder15_4.setText(_translate("Dialog", "Roma: 1° posto"))
        self.labelOver15_4.setText(_translate("Dialog", "Udinese: 10° posto"))
        self.labelProbabilitaEsito_4.setText(_translate("Dialog", "🏠 --- In Casa ---"))
        self.labelProbabilitaVittoria_4.setText(_translate("Dialog", "Roma: 8° posto"))
        self.labelProbabilitaPareggio_4.setText(_translate("Dialog", "Udinese: 10° posto"))
        self.labelPredizioneGoal_4.setText(_translate("Dialog", "📊 --- Generale ---"))
        self.labelGoalPrevisti_4.setText(_translate("Dialog", "Roma: 6° posto"))
        self.labelEsitoPrevisto_4.setText(_translate("Dialog", "Udinese: 9° posto"))
        self.labelPredizioni_5.setText(_translate("Dialog", "📈 Statistiche Storiche Aggregate"))
        self.labelUnderOver_5.setText(_translate("Dialog", "📅 ULTIME 5 PARTITE TRA LE DUE SQUADRE"))
        self.labelUnder15_5.setText(_translate("Dialog", "16/Apr: Roma 3-0 Udinese"))
        self.labelOver15_5.setText(_translate("Dialog", "26/Nov: Roma 3-1 Udinese"))
        self.labelOver15_6.setText(_translate("Dialog", "25/Apr: Udinese 1-2 Roma"))
        self.labelOver15_7.setText(_translate("Dialog", "22/Set: Roma 3-0 Udinese"))
        self.labelOver15_8.setText(_translate("Dialog", "26/Gen: Udinese 1-2 Roma"))
        self.labelProbabilitaEsito_5.setText(_translate("Dialog", "=== SCONTRI DIRETTI STORICI ==="))
        self.labelProbabilitaVittoria_5.setText(_translate("Dialog", "Trovati 12 scontri diretti storici"))
        self.labelProbabilitaPareggio_5.setText(_translate("Dialog", "🏆 BILANCIO SCONTRI DIRETTI:"))
        self.labelProbabilitaVittoria_6.setText(_translate("Dialog", "Roma: 9 vittorie"))
        self.labelProbabilitaVittoria_7.setText(_translate("Dialog", "Udinese: 2 vittorie"))
        self.labelProbabilitaVittoria_8.setText(_translate("Dialog", "Pareggi: 1"))
        self.labelPredizioneGoal_5.setText(_translate("Dialog", "--- Partite Precedenti ---"))
        self.labelGoalPrevisti_5.setText(_translate("Dialog", "Roma: 228 partite, 113-51-64, 375-271"))
        self.labelEsitoPrevisto_5.setText(_translate("Dialog", "Udinese: 228 partite, 62-73-93, 265-324"))
        self.labelTestataEsitiDalRanking_2.setText(_translate("Dialog", "=== Analisi e Raccomandazioni ==="))
        self.labelPredizioni_6.setText(_translate("Dialog", "**🎯SCOMMESSA CONSIGLIATA**"))
        self.labelFormaRecente_3.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_3.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_3.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_14.setText(_translate("Dialog", "Doppia Chance 1X (Casa o Pareggio)"))
        self.labelGoalPrevisti_6.setText(_translate("Dialog", "Probabilità di successo: 95%"))
        self.labelEsitoPrevisto_6.setText(_translate("Dialog", "Livello rischio: 🟢 BASSO"))
        self.labelPredizioni_12.setText(_translate("Dialog", "**SCOMMESSA CONSIGLIATA**"))
        self.labelFormaRecente_6.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_6.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_6.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_12.setText(_translate("Dialog", "Probabilità di successo: 95%"))
        self.labelEsitoPrevisto_12.setText(_translate("Dialog", "Livello rischio: 🟢 BASSO"))
        self.labelPredizioni_13.setText(_translate("Dialog", "**📊ALTRE OPZIONI INTERESSANTI:**"))
        self.labelFormaRecente_7.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_7.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_7.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_13.setText(_translate("Dialog", "Probabilità di successo: 95%"))
        self.labelEsitoPrevisto_13.setText(_translate("Dialog", "Combo suggerita: 1 + Under 2.5"))
        self.labelPredizioni_7.setText(_translate("Dialog", "🧠 **MOTIVAZIONE TECNICA:**"))
        self.labelFormaRecente_4.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_4.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_4.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_15.setText(_translate("Dialog", "📊 Predizione esito: Roma favorito con 85% di probabilità"))
        self.labelGoalPrevisti_7.setText(_translate("Dialog", "⚽ Goal previsti: Roma vs Udinese → 2.1 goal totali"))
        self.labelEsitoPrevisto_7.setText(_translate("Dialog", "🔥 Forma recente: Roma in forma migliore (1.8 vs 1.4)"))
        self.labelEsitoPrevisto_8.setText(_translate("Dialog", "🏆 Ranking attuale: Roma meglio classificato (2° vs 10°)"))
        self.labelEsitoPrevisto_9.setText(_translate("Dialog", "⚔️  Scontri diretti: Roma dominante (9-2-1)"))
        self.labelPredizioni_8.setText(_translate("Dialog", "💡 **COMMENTO FINALE AI:**"))
        self.labelFormaRecente_8.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_8.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_8.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_16.setText(_translate("Dialog", "Indicatori contrastanti. La scommessa consigliata è la più prudente."))
        self.labelGoalPrevisti_8.setText(_translate("Dialog", "🟢 **Confidenza ALTA** - Scommessa consigliata con ottime probabilità di successo."))
        self.labelPredizioni_9.setText(_translate("Dialog", "🧠 **MOTIVAZIONE TECNICA:**"))
        self.labelFormaRecente_9.setText(_translate("Dialog", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_9.setText(_translate("Dialog", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_9.setText(_translate("Dialog", "Udinese: 1.6/3.0 punti/partita"))
        self.labelGoalPrevisti_17.setText(_translate("Dialog", "📊 Predizione esito: Roma favorito con 85% di probabilità"))
        self.labelGoalPrevisti_9.setText(_translate("Dialog", "⚽ Goal previsti: Roma vs Udinese → 2.1 goal totali"))
        self.labelEsitoPrevisto_10.setText(_translate("Dialog", "🔥 Forma recente: Roma in forma migliore (1.8 vs 1.4)"))
        self.labelEsitoPrevisto_14.setText(_translate("Dialog", "🏆 Ranking attuale: Roma meglio classificato (2° vs 10°)"))
        self.labelEsitoPrevisto_15.setText(_translate("Dialog", "⚔️  Scontri diretti: Roma dominante (9-2-1)"))
