# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Predizioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1907, 3945)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));\n"
"color:white;\n"
"font: 12pt \"Segoe UI\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollAreaRanking = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaRanking.setGeometry(QtCore.QRect(10, 200, 1900, 800))
        self.scrollAreaRanking.setStyleSheet("")
        self.scrollAreaRanking.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaRanking.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaRanking.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollAreaRanking.setWidgetResizable(True)
        self.scrollAreaRanking.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollAreaRanking.setObjectName("scrollAreaRanking")
        self.scrollAreaWidgetEsitiRanking = QtWidgets.QWidget()
        self.scrollAreaWidgetEsitiRanking.setGeometry(QtCore.QRect(0, 0, 1881, 6000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetEsitiRanking.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetEsitiRanking.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetEsitiRanking.setMinimumSize(QtCore.QSize(1881, 6000))
        self.scrollAreaWidgetEsitiRanking.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetEsitiRanking.setStyleSheet("background: transparent;")
        self.scrollAreaWidgetEsitiRanking.setObjectName("scrollAreaWidgetEsitiRanking")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetEsitiRanking)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 1861, 5900))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VerticalLayOut = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VerticalLayOut.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayOut.setSpacing(6)
        self.VerticalLayOut.setObjectName("VerticalLayOut")
        self.FramePrincipale = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.FramePrincipale.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FramePrincipale.sizePolicy().hasHeightForWidth())
        self.FramePrincipale.setSizePolicy(sizePolicy)
        self.FramePrincipale.setStyleSheet("background: transparent;")
        self.FramePrincipale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FramePrincipale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FramePrincipale.setObjectName("FramePrincipale")
        self.frameEsitiRanking = QtWidgets.QFrame(self.FramePrincipale)
        self.frameEsitiRanking.setGeometry(QtCore.QRect(10, 10, 1861, 561))
        self.frameEsitiRanking.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.frameEsitiRanking.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEsitiRanking.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEsitiRanking.setObjectName("frameEsitiRanking")
        self.labelTestataEsitiDalRanking = QtWidgets.QLabel(self.frameEsitiRanking)
        self.labelTestataEsitiDalRanking.setGeometry(QtCore.QRect(475, 0, 950, 31))
        self.labelTestataEsitiDalRanking.setStyleSheet("color: rgb(58, 255, 65);\n"
"font:  16pt \"Segoe UI Black\";\n"
"background: transparent;")
        self.labelTestataEsitiDalRanking.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataEsitiDalRanking.setObjectName("labelTestataEsitiDalRanking")
        self.line = QtWidgets.QFrame(self.frameEsitiRanking)
        self.line.setGeometry(QtCore.QRect(7, 40, 1841, 20))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.framePredizioni = QtWidgets.QFrame(self.frameEsitiRanking)
        self.framePredizioni.setGeometry(QtCore.QRect(10, 62, 361, 485))
        self.framePredizioni.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni.setObjectName("framePredizioni")
        self.labelPredizioni = QtWidgets.QLabel(self.framePredizioni)
        self.labelPredizioni.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni.setObjectName("labelPredizioni")
        self.frameFormaRecente = QtWidgets.QFrame(self.framePredizioni)
        self.frameFormaRecente.setGeometry(QtCore.QRect(10, 400, 341, 91))
        self.frameFormaRecente.setStyleSheet("background: transparent;")
        self.frameFormaRecente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente.setObjectName("frameFormaRecente")
        self.labelFormaRecente = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecente.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente.setObjectName("labelFormaRecente")
        self.labelFormaRecenteSquadraDiCasa = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecenteSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa.setObjectName("labelFormaRecenteSquadraDiCasa")
        self.labelFormaRecenteSquadraInTrasferta = QtWidgets.QLabel(self.frameFormaRecente)
        self.labelFormaRecenteSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta.setObjectName("labelFormaRecenteSquadraInTrasferta")
        self.frameUnderOver = QtWidgets.QFrame(self.framePredizioni)
        self.frameUnderOver.setGeometry(QtCore.QRect(10, 267, 341, 131))
        self.frameUnderOver.setStyleSheet("background: transparent;")
        self.frameUnderOver.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnderOver.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnderOver.setObjectName("frameUnderOver")
        self.labelUnderOver = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnderOver.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelUnderOver.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUnderOver.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnderOver.setObjectName("labelUnderOver")
        self.labelUnder15 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnder15.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelUnder15.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder15.setObjectName("labelUnder15")
        self.labelOver15 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelOver15.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelOver15.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver15.setObjectName("labelOver15")
        self.labelUnder25 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelUnder25.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelUnder25.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUnder25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUnder25.setObjectName("labelUnder25")
        self.labelOver25 = QtWidgets.QLabel(self.frameUnderOver)
        self.labelOver25.setGeometry(QtCore.QRect(10, 105, 301, 21))
        self.labelOver25.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelOver25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOver25.setObjectName("labelOver25")
        self.frameProbabilitaEsito = QtWidgets.QFrame(self.framePredizioni)
        self.frameProbabilitaEsito.setGeometry(QtCore.QRect(10, 153, 341, 111))
        self.frameProbabilitaEsito.setStyleSheet("background: transparent;")
        self.frameProbabilitaEsito.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito.setObjectName("frameProbabilitaEsito")
        self.labelProbabilitaEsito = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaEsito.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelProbabilitaEsito.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelProbabilitaEsito.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProbabilitaEsito.setObjectName("labelProbabilitaEsito")
        self.labelProbabilitaVittoria = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaVittoria.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelProbabilitaVittoria.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaVittoria.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProbabilitaVittoria.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelProbabilitaVittoria.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaVittoria.setObjectName("labelProbabilitaVittoria")
        self.labelProbabilitaPareggio = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaPareggio.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelProbabilitaPareggio.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaPareggio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaPareggio.setObjectName("labelProbabilitaPareggio")
        self.labelProbabilitaSconfitta = QtWidgets.QLabel(self.frameProbabilitaEsito)
        self.labelProbabilitaSconfitta.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelProbabilitaSconfitta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelProbabilitaSconfitta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProbabilitaSconfitta.setObjectName("labelProbabilitaSconfitta")
        self.framePredizioneGoal = QtWidgets.QFrame(self.framePredizioni)
        self.framePredizioneGoal.setGeometry(QtCore.QRect(10, 39, 341, 111))
        self.framePredizioneGoal.setStyleSheet("background: transparent;")
        self.framePredizioneGoal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioneGoal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioneGoal.setObjectName("framePredizioneGoal")
        self.labelPredizioneGoal = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelPredizioneGoal.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioneGoal.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioneGoal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioneGoal.setObjectName("labelPredizioneGoal")
        self.labelGoalPrevisti = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelGoalPrevisti.setGeometry(QtCore.QRect(10, 40, 341, 21))
        self.labelGoalPrevisti.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelGoalPrevisti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGoalPrevisti.setObjectName("labelGoalPrevisti")
        self.labelEsitoPrevisto = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelEsitoPrevisto.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelEsitoPrevisto.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelEsitoPrevisto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEsitoPrevisto.setObjectName("labelEsitoPrevisto")
        self.labelDoppiaChanceSuggerita = QtWidgets.QLabel(self.framePredizioneGoal)
        self.labelDoppiaChanceSuggerita.setGeometry(QtCore.QRect(10, 84, 301, 21))
        self.labelDoppiaChanceSuggerita.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelDoppiaChanceSuggerita.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDoppiaChanceSuggerita.setObjectName("labelDoppiaChanceSuggerita")
        self.frameRankingCampionatiPrecedenti = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRankingCampionatiPrecedenti.setGeometry(QtCore.QRect(380, 62, 361, 485))
        self.frameRankingCampionatiPrecedenti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatiPrecedenti.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatiPrecedenti.setObjectName("frameRankingCampionatiPrecedenti")
        self.labelPredizioni_2 = QtWidgets.QLabel(self.frameRankingCampionatiPrecedenti)
        self.labelPredizioni_2.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelPredizioni_2.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelPredizioni_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredizioni_2.setObjectName("labelPredizioni_2")
        self.frameStatisticheStoricheAggregate = QtWidgets.QFrame(self.frameRankingCampionatiPrecedenti)
        self.frameStatisticheStoricheAggregate.setGeometry(QtCore.QRect(10, 380, 321, 91))
        self.frameStatisticheStoricheAggregate.setStyleSheet("background: transparent;")
        self.frameStatisticheStoricheAggregate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStatisticheStoricheAggregate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStatisticheStoricheAggregate.setObjectName("frameStatisticheStoricheAggregate")
        self.labelStatisticheStoricheAggregate = QtWidgets.QLabel(self.frameStatisticheStoricheAggregate)
        self.labelStatisticheStoricheAggregate.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelStatisticheStoricheAggregate.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelStatisticheStoricheAggregate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatisticheStoricheAggregate.setObjectName("labelStatisticheStoricheAggregate")
        self.labelStatisticheStoricheAggregateSquadraDiCasa = QtWidgets.QLabel(self.frameStatisticheStoricheAggregate)
        self.labelStatisticheStoricheAggregateSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelStatisticheStoricheAggregateSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelStatisticheStoricheAggregateSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStatisticheStoricheAggregateSquadraDiCasa.setObjectName("labelStatisticheStoricheAggregateSquadraDiCasa")
        self.labelStatisticheStoricheAggregateSquadraInTrasferta = QtWidgets.QLabel(self.frameStatisticheStoricheAggregate)
        self.labelStatisticheStoricheAggregateSquadraInTrasferta.setGeometry(QtCore.QRect(10, 60, 301, 21))
        self.labelStatisticheStoricheAggregateSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelStatisticheStoricheAggregateSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStatisticheStoricheAggregateSquadraInTrasferta.setObjectName("labelStatisticheStoricheAggregateSquadraInTrasferta")
        self.frameRankingCampionatiPrecedentiInTraferta = QtWidgets.QFrame(self.frameRankingCampionatiPrecedenti)
        self.frameRankingCampionatiPrecedentiInTraferta.setGeometry(QtCore.QRect(10, 270, 321, 91))
        self.frameRankingCampionatiPrecedentiInTraferta.setStyleSheet("background: transparent;")
        self.frameRankingCampionatiPrecedentiInTraferta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatiPrecedentiInTraferta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatiPrecedentiInTraferta.setObjectName("frameRankingCampionatiPrecedentiInTraferta")
        self.labelRankingCampionatiPrecedentiInTraferta = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInTraferta)
        self.labelRankingCampionatiPrecedentiInTraferta.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatiPrecedentiInTraferta.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatiPrecedentiInTraferta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatiPrecedentiInTraferta.setObjectName("labelRankingCampionatiPrecedentiInTraferta")
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInTraferta)
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa.setObjectName("labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa")
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInTraferta)
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"")
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta.setObjectName("labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta")
        self.frameRankingCampionatiPrecedentiInCasa = QtWidgets.QFrame(self.frameRankingCampionatiPrecedenti)
        self.frameRankingCampionatiPrecedentiInCasa.setGeometry(QtCore.QRect(10, 150, 321, 111))
        self.frameRankingCampionatiPrecedentiInCasa.setStyleSheet("background: transparent;")
        self.frameRankingCampionatiPrecedentiInCasa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatiPrecedentiInCasa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatiPrecedentiInCasa.setObjectName("frameRankingCampionatiPrecedentiInCasa")
        self.labelRankingCampionatiPrecedentiInCasa = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInCasa)
        self.labelRankingCampionatiPrecedentiInCasa.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatiPrecedentiInCasa.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatiPrecedentiInCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatiPrecedentiInCasa.setObjectName("labelRankingCampionatiPrecedentiInCasa")
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInCasa)
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"")
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa.setObjectName("labelRankingCampionatiPrecedentiInCasaSquadraDiCasa")
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiInCasa)
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta.setObjectName("labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta")
        self.frameRankingCampionatiPrecedentiGenerale = QtWidgets.QFrame(self.frameRankingCampionatiPrecedenti)
        self.frameRankingCampionatiPrecedentiGenerale.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.frameRankingCampionatiPrecedentiGenerale.setStyleSheet("background: transparent;")
        self.frameRankingCampionatiPrecedentiGenerale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatiPrecedentiGenerale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatiPrecedentiGenerale.setObjectName("frameRankingCampionatiPrecedentiGenerale")
        self.labelRankingCampionatiPrecedentiGenerale = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiGenerale)
        self.labelRankingCampionatiPrecedentiGenerale.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatiPrecedentiGenerale.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatiPrecedentiGenerale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatiPrecedentiGenerale.setObjectName("labelRankingCampionatiPrecedentiGenerale")
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiGenerale)
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa.setObjectName("labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa")
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatiPrecedentiGenerale)
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta.setObjectName("labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta")
        self.frameRankingCampionatoAttuale = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRankingCampionatoAttuale.setGeometry(QtCore.QRect(750, 62, 351, 485))
        self.frameRankingCampionatoAttuale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatoAttuale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatoAttuale.setObjectName("frameRankingCampionatoAttuale")
        self.labelRankingCampionatoAttuale = QtWidgets.QLabel(self.frameRankingCampionatoAttuale)
        self.labelRankingCampionatoAttuale.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatoAttuale.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatoAttuale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatoAttuale.setObjectName("labelRankingCampionatoAttuale")
        self.frameRankingCampionatoAttualeInTraferta = QtWidgets.QFrame(self.frameRankingCampionatoAttuale)
        self.frameRankingCampionatoAttualeInTraferta.setGeometry(QtCore.QRect(10, 360, 321, 121))
        self.frameRankingCampionatoAttualeInTraferta.setStyleSheet("background: transparent;")
        self.frameRankingCampionatoAttualeInTraferta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatoAttualeInTraferta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatoAttualeInTraferta.setObjectName("frameRankingCampionatoAttualeInTraferta")
        self.labelRankingCampionatoAttualeInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInTraferta)
        self.labelRankingCampionatoAttualeInTrasferta.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatoAttualeInTrasferta.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatoAttualeInTrasferta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatoAttualeInTrasferta.setObjectName("labelRankingCampionatoAttualeInTrasferta")
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInTraferta)
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa.setObjectName("labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa")
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInTraferta)
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"\n"
"")
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta.setObjectName("labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta")
        self.frameRankingCampionatoAttualeInCasa = QtWidgets.QFrame(self.frameRankingCampionatoAttuale)
        self.frameRankingCampionatoAttualeInCasa.setGeometry(QtCore.QRect(10, 190, 321, 111))
        self.frameRankingCampionatoAttualeInCasa.setStyleSheet("background: transparent;")
        self.frameRankingCampionatoAttualeInCasa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatoAttualeInCasa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatoAttualeInCasa.setObjectName("frameRankingCampionatoAttualeInCasa")
        self.labelRankingCampionatoAttualeInCasa = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInCasa)
        self.labelRankingCampionatoAttualeInCasa.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatoAttualeInCasa.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatoAttualeInCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatoAttualeInCasa.setObjectName("labelRankingCampionatoAttualeInCasa")
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInCasa)
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"")
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa.setObjectName("labelRankingCampionatoAttualeInCasaSquadraDiCasa")
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatoAttualeInCasa)
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta.setObjectName("labelRankingCampionatoAttualeInCasaSquadraInTrasferta")
        self.frameRankingCampionatoAttualeGenerale = QtWidgets.QFrame(self.frameRankingCampionatoAttuale)
        self.frameRankingCampionatoAttualeGenerale.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.frameRankingCampionatoAttualeGenerale.setStyleSheet("background: transparent;")
        self.frameRankingCampionatoAttualeGenerale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingCampionatoAttualeGenerale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingCampionatoAttualeGenerale.setObjectName("frameRankingCampionatoAttualeGenerale")
        self.labelRankingCampionatoAttualeGenerale = QtWidgets.QLabel(self.frameRankingCampionatoAttualeGenerale)
        self.labelRankingCampionatoAttualeGenerale.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingCampionatoAttualeGenerale.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingCampionatoAttualeGenerale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingCampionatoAttualeGenerale.setObjectName("labelRankingCampionatoAttualeGenerale")
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa = QtWidgets.QLabel(self.frameRankingCampionatoAttualeGenerale)
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa.setObjectName("labelRankingCampionatoAttualeGeneraleSquadraDiCasa")
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingCampionatoAttualeGenerale)
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta.setObjectName("labelRankingCampionatoAttualeGeneraleSquadraInTrasferta")
        self.frameRankingUltime5Partite = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameRankingUltime5Partite.setGeometry(QtCore.QRect(1110, 61, 351, 485))
        self.frameRankingUltime5Partite.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingUltime5Partite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingUltime5Partite.setObjectName("frameRankingUltime5Partite")
        self.labelRankingUltime5Partite = QtWidgets.QLabel(self.frameRankingUltime5Partite)
        self.labelRankingUltime5Partite.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingUltime5Partite.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingUltime5Partite.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingUltime5Partite.setObjectName("labelRankingUltime5Partite")
        self.frameRankingUltime5PartiteInTrasferta = QtWidgets.QFrame(self.frameRankingUltime5Partite)
        self.frameRankingUltime5PartiteInTrasferta.setGeometry(QtCore.QRect(10, 360, 321, 131))
        self.frameRankingUltime5PartiteInTrasferta.setStyleSheet("background: transparent;")
        self.frameRankingUltime5PartiteInTrasferta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingUltime5PartiteInTrasferta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingUltime5PartiteInTrasferta.setObjectName("frameRankingUltime5PartiteInTrasferta")
        self.labelRankingUltime5PartiteInTrasferta = QtWidgets.QLabel(self.frameRankingUltime5PartiteInTrasferta)
        self.labelRankingUltime5PartiteInTrasferta.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingUltime5PartiteInTrasferta.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingUltime5PartiteInTrasferta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingUltime5PartiteInTrasferta.setObjectName("labelRankingUltime5PartiteInTrasferta")
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa = QtWidgets.QLabel(self.frameRankingUltime5PartiteInTrasferta)
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa.setObjectName("labelRankingUltime5PartiteInTrasfertaSquadraDiCasa")
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingUltime5PartiteInTrasferta)
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"\n"
"")
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta.setObjectName("labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta")
        self.frameRankingUltime5PartiteInCasa = QtWidgets.QFrame(self.frameRankingUltime5Partite)
        self.frameRankingUltime5PartiteInCasa.setGeometry(QtCore.QRect(10, 190, 321, 111))
        self.frameRankingUltime5PartiteInCasa.setStyleSheet("background: transparent;")
        self.frameRankingUltime5PartiteInCasa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingUltime5PartiteInCasa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingUltime5PartiteInCasa.setObjectName("frameRankingUltime5PartiteInCasa")
        self.labelRankingUltime5PartiteInCasa = QtWidgets.QLabel(self.frameRankingUltime5PartiteInCasa)
        self.labelRankingUltime5PartiteInCasa.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingUltime5PartiteInCasa.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingUltime5PartiteInCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingUltime5PartiteInCasa.setObjectName("labelRankingUltime5PartiteInCasa")
        self.labelRankingUltime5PartiteInCasaSquadraDiCara = QtWidgets.QLabel(self.frameRankingUltime5PartiteInCasa)
        self.labelRankingUltime5PartiteInCasaSquadraDiCara.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingUltime5PartiteInCasaSquadraDiCara.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background-color: rgb(25, 33, 145);\n"
"\n"
"")
        self.labelRankingUltime5PartiteInCasaSquadraDiCara.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteInCasaSquadraDiCara.setObjectName("labelRankingUltime5PartiteInCasaSquadraDiCara")
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingUltime5PartiteInCasa)
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta.setObjectName("labelRankingUltime5PartiteInCasaSquadraInTrasferta")
        self.frameRankingUltime5PartiteGenerale = QtWidgets.QFrame(self.frameRankingUltime5Partite)
        self.frameRankingUltime5PartiteGenerale.setGeometry(QtCore.QRect(10, 39, 321, 111))
        self.frameRankingUltime5PartiteGenerale.setStyleSheet("background: transparent;")
        self.frameRankingUltime5PartiteGenerale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRankingUltime5PartiteGenerale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRankingUltime5PartiteGenerale.setObjectName("frameRankingUltime5PartiteGenerale")
        self.labelRankingUltime5PartiteGenerale = QtWidgets.QLabel(self.frameRankingUltime5PartiteGenerale)
        self.labelRankingUltime5PartiteGenerale.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelRankingUltime5PartiteGenerale.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelRankingUltime5PartiteGenerale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankingUltime5PartiteGenerale.setObjectName("labelRankingUltime5PartiteGenerale")
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa = QtWidgets.QLabel(self.frameRankingUltime5PartiteGenerale)
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa.setObjectName("labelRankingUltime5PartiteGeneraleSqaudraDiCasa")
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta = QtWidgets.QLabel(self.frameRankingUltime5PartiteGenerale)
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta.setObjectName("labelRankingUltime5PartiteGeneraleSquadraInTrasferta")
        self.frameScontriStoriciDiretti = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameScontriStoriciDiretti.setGeometry(QtCore.QRect(1480, 60, 351, 485))
        self.frameScontriStoriciDiretti.setStyleSheet("background:transparent;")
        self.frameScontriStoriciDiretti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameScontriStoriciDiretti.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameScontriStoriciDiretti.setObjectName("frameScontriStoriciDiretti")
        self.labelScontriStoriciDiretti = QtWidgets.QLabel(self.frameScontriStoriciDiretti)
        self.labelScontriStoriciDiretti.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.labelScontriStoriciDiretti.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelScontriStoriciDiretti.setAlignment(QtCore.Qt.AlignCenter)
        self.labelScontriStoriciDiretti.setObjectName("labelScontriStoriciDiretti")
        self.labelScontriTrovati = QtWidgets.QLabel(self.frameScontriStoriciDiretti)
        self.labelScontriTrovati.setGeometry(QtCore.QRect(10, 50, 321, 21))
        self.labelScontriTrovati.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelScontriTrovati.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScontriTrovati.setObjectName("labelScontriTrovati")
        self.frameUltime5PartiteTraLe2Squadre = QtWidgets.QFrame(self.frameScontriStoriciDiretti)
        self.frameUltime5PartiteTraLe2Squadre.setGeometry(QtCore.QRect(10, 219, 321, 151))
        self.frameUltime5PartiteTraLe2Squadre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUltime5PartiteTraLe2Squadre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUltime5PartiteTraLe2Squadre.setObjectName("frameUltime5PartiteTraLe2Squadre")
        self.labelUltime5PartiteTraLe2Squadre = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre.setGeometry(QtCore.QRect(0, 10, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelUltime5PartiteTraLe2Squadre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUltime5PartiteTraLe2Squadre.setObjectName("labelUltime5PartiteTraLe2Squadre")
        self.labelUltime5PartiteTraLe2Squadre_3 = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre_3.setGeometry(QtCore.QRect(10, 90, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUltime5PartiteTraLe2Squadre_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUltime5PartiteTraLe2Squadre_3.setObjectName("labelUltime5PartiteTraLe2Squadre_3")
        self.labelUltime5PartiteTraLe2Squadre_5 = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre_5.setGeometry(QtCore.QRect(10, 130, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre_5.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUltime5PartiteTraLe2Squadre_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUltime5PartiteTraLe2Squadre_5.setObjectName("labelUltime5PartiteTraLe2Squadre_5")
        self.labelUltime5PartiteTraLe2Squadre_4 = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre_4.setGeometry(QtCore.QRect(10, 110, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre_4.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUltime5PartiteTraLe2Squadre_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUltime5PartiteTraLe2Squadre_4.setObjectName("labelUltime5PartiteTraLe2Squadre_4")
        self.labelUltime5PartiteTraLe2Squadre_2 = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre_2.setGeometry(QtCore.QRect(10, 72, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre_2.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUltime5PartiteTraLe2Squadre_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUltime5PartiteTraLe2Squadre_2.setObjectName("labelUltime5PartiteTraLe2Squadre_2")
        self.labelUltime5PartiteTraLe2Squadre_1 = QtWidgets.QLabel(self.frameUltime5PartiteTraLe2Squadre)
        self.labelUltime5PartiteTraLe2Squadre_1.setGeometry(QtCore.QRect(10, 50, 321, 21))
        self.labelUltime5PartiteTraLe2Squadre_1.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelUltime5PartiteTraLe2Squadre_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUltime5PartiteTraLe2Squadre_1.setObjectName("labelUltime5PartiteTraLe2Squadre_1")
        self.frameBilancioScontriDiretti = QtWidgets.QFrame(self.frameScontriStoriciDiretti)
        self.frameBilancioScontriDiretti.setGeometry(QtCore.QRect(10, 80, 321, 141))
        self.frameBilancioScontriDiretti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBilancioScontriDiretti.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBilancioScontriDiretti.setObjectName("frameBilancioScontriDiretti")
        self.labelBilancioScontriDirettiPareggi = QtWidgets.QLabel(self.frameBilancioScontriDiretti)
        self.labelBilancioScontriDirettiPareggi.setGeometry(QtCore.QRect(10, 80, 321, 21))
        self.labelBilancioScontriDirettiPareggi.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelBilancioScontriDirettiPareggi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBilancioScontriDirettiPareggi.setObjectName("labelBilancioScontriDirettiPareggi")
        self.labelBilancioScontriDiretti = QtWidgets.QLabel(self.frameBilancioScontriDiretti)
        self.labelBilancioScontriDiretti.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.labelBilancioScontriDiretti.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"\n"
"")
        self.labelBilancioScontriDiretti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBilancioScontriDiretti.setObjectName("labelBilancioScontriDiretti")
        self.labelBilancioScontriDirettiSquadraDiCasa = QtWidgets.QLabel(self.frameBilancioScontriDiretti)
        self.labelBilancioScontriDirettiSquadraDiCasa.setGeometry(QtCore.QRect(10, 40, 321, 21))
        self.labelBilancioScontriDirettiSquadraDiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelBilancioScontriDirettiSquadraDiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBilancioScontriDirettiSquadraDiCasa.setObjectName("labelBilancioScontriDirettiSquadraDiCasa")
        self.labelBilancioScontriDirettiSquadraInTrasferta = QtWidgets.QLabel(self.frameBilancioScontriDiretti)
        self.labelBilancioScontriDirettiSquadraInTrasferta.setGeometry(QtCore.QRect(10, 60, 321, 21))
        self.labelBilancioScontriDirettiSquadraInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelBilancioScontriDirettiSquadraInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBilancioScontriDirettiSquadraInTrasferta.setObjectName("labelBilancioScontriDirettiSquadraInTrasferta")
        self.frameProbabilitaEsito_5 = QtWidgets.QFrame(self.frameEsitiRanking)
        self.frameProbabilitaEsito_5.setGeometry(QtCore.QRect(1630, 190, 331, 161))
        self.frameProbabilitaEsito_5.setStyleSheet("background: transparent;")
        self.frameProbabilitaEsito_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProbabilitaEsito_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProbabilitaEsito_5.setObjectName("frameProbabilitaEsito_5")
        self.frameEsitiRanking_2 = QtWidgets.QFrame(self.FramePrincipale)
        self.frameEsitiRanking_2.setGeometry(QtCore.QRect(40, 700, 1861, 1251))
        self.frameEsitiRanking_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.frameEsitiRanking_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEsitiRanking_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEsitiRanking_2.setLineWidth(0)
        self.frameEsitiRanking_2.setObjectName("frameEsitiRanking_2")
        self.labelTestataEsitiDalRanking_2 = QtWidgets.QLabel(self.frameEsitiRanking_2)
        self.labelTestataEsitiDalRanking_2.setGeometry(QtCore.QRect(475, 0, 950, 31))
        self.labelTestataEsitiDalRanking_2.setStyleSheet("color: rgb(58, 255, 65);\n"
"font:  16pt \"Segoe UI Black\";\n"
"background: transparent;")
        self.labelTestataEsitiDalRanking_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataEsitiDalRanking_2.setObjectName("labelTestataEsitiDalRanking_2")
        self.line_2 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.line_2.setGeometry(QtCore.QRect(7, 40, 1841, 20))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frameScommessaConsigliata = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.frameScommessaConsigliata.setGeometry(QtCore.QRect(10, 61, 511, 101))
        self.frameScommessaConsigliata.setStyleSheet("")
        self.frameScommessaConsigliata.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameScommessaConsigliata.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameScommessaConsigliata.setObjectName("frameScommessaConsigliata")
        self.labelScommessaConsigliata = QtWidgets.QLabel(self.frameScommessaConsigliata)
        self.labelScommessaConsigliata.setGeometry(QtCore.QRect(100, 0, 301, 21))
        self.labelScommessaConsigliata.setStyleSheet("background:transparent;\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelScommessaConsigliata.setAlignment(QtCore.Qt.AlignCenter)
        self.labelScommessaConsigliata.setObjectName("labelScommessaConsigliata")
        self.labelScommessaConsigliataDoppiaChance = QtWidgets.QLabel(self.frameScommessaConsigliata)
        self.labelScommessaConsigliataDoppiaChance.setGeometry(QtCore.QRect(20, 30, 481, 21))
        self.labelScommessaConsigliataDoppiaChance.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelScommessaConsigliataDoppiaChance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScommessaConsigliataDoppiaChance.setObjectName("labelScommessaConsigliataDoppiaChance")
        self.labelScommessaConsigliataProbabilitaSuccesso = QtWidgets.QLabel(self.frameScommessaConsigliata)
        self.labelScommessaConsigliataProbabilitaSuccesso.setGeometry(QtCore.QRect(20, 50, 481, 21))
        self.labelScommessaConsigliataProbabilitaSuccesso.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelScommessaConsigliataProbabilitaSuccesso.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScommessaConsigliataProbabilitaSuccesso.setObjectName("labelScommessaConsigliataProbabilitaSuccesso")
        self.labelScommessaConsigliataLivelloRischio = QtWidgets.QLabel(self.frameScommessaConsigliata)
        self.labelScommessaConsigliataLivelloRischio.setGeometry(QtCore.QRect(20, 70, 481, 21))
        self.labelScommessaConsigliataLivelloRischio.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelScommessaConsigliataLivelloRischio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScommessaConsigliataLivelloRischio.setObjectName("labelScommessaConsigliataLivelloRischio")
        self.frameAltreOpzioni = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.frameAltreOpzioni.setGeometry(QtCore.QRect(10, 170, 511, 61))
        self.frameAltreOpzioni.setStyleSheet("")
        self.frameAltreOpzioni.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAltreOpzioni.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAltreOpzioni.setObjectName("frameAltreOpzioni")
        self.labelframeAltreOpzioni = QtWidgets.QLabel(self.frameAltreOpzioni)
        self.labelframeAltreOpzioni.setGeometry(QtCore.QRect(100, 10, 301, 21))
        self.labelframeAltreOpzioni.setStyleSheet("background:transparent;\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelframeAltreOpzioni.setAlignment(QtCore.Qt.AlignCenter)
        self.labelframeAltreOpzioni.setObjectName("labelframeAltreOpzioni")
        self.labelAltreOpzioniSuggerimenti = QtWidgets.QLabel(self.frameAltreOpzioni)
        self.labelAltreOpzioniSuggerimenti.setGeometry(QtCore.QRect(20, 30, 481, 21))
        self.labelAltreOpzioniSuggerimenti.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelAltreOpzioniSuggerimenti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAltreOpzioniSuggerimenti.setObjectName("labelAltreOpzioniSuggerimenti")
        self.frameMotivazioneTecnica = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.frameMotivazioneTecnica.setGeometry(QtCore.QRect(630, 61, 430, 151))
        self.frameMotivazioneTecnica.setStyleSheet("")
        self.frameMotivazioneTecnica.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMotivazioneTecnica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMotivazioneTecnica.setObjectName("frameMotivazioneTecnica")
        self.labelMotivazioneTecnica = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnica.setGeometry(QtCore.QRect(60, 0, 301, 21))
        self.labelMotivazioneTecnica.setStyleSheet("background:transparent;\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelMotivazioneTecnica.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMotivazioneTecnica.setObjectName("labelMotivazioneTecnica")
        self.labelMotivazioneTecnicaPredizione = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnicaPredizione.setGeometry(QtCore.QRect(20, 30, 400, 21))
        self.labelMotivazioneTecnicaPredizione.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelMotivazioneTecnicaPredizione.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMotivazioneTecnicaPredizione.setObjectName("labelMotivazioneTecnicaPredizione")
        self.labelMotivazioneTecnicaGoalsPrevisti = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnicaGoalsPrevisti.setGeometry(QtCore.QRect(20, 50, 400, 21))
        self.labelMotivazioneTecnicaGoalsPrevisti.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelMotivazioneTecnicaGoalsPrevisti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMotivazioneTecnicaGoalsPrevisti.setObjectName("labelMotivazioneTecnicaGoalsPrevisti")
        self.labelMotivazioneTecnicaFormaRecente = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnicaFormaRecente.setGeometry(QtCore.QRect(20, 70, 400, 21))
        self.labelMotivazioneTecnicaFormaRecente.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelMotivazioneTecnicaFormaRecente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMotivazioneTecnicaFormaRecente.setObjectName("labelMotivazioneTecnicaFormaRecente")
        self.labelMotivazioneTecnicaRankingAttuale = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnicaRankingAttuale.setGeometry(QtCore.QRect(20, 90, 400, 21))
        self.labelMotivazioneTecnicaRankingAttuale.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelMotivazioneTecnicaRankingAttuale.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMotivazioneTecnicaRankingAttuale.setObjectName("labelMotivazioneTecnicaRankingAttuale")
        self.labelMotivazioneTecnicaScontriDiretti = QtWidgets.QLabel(self.frameMotivazioneTecnica)
        self.labelMotivazioneTecnicaScontriDiretti.setGeometry(QtCore.QRect(20, 110, 400, 21))
        self.labelMotivazioneTecnicaScontriDiretti.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelMotivazioneTecnicaScontriDiretti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMotivazioneTecnicaScontriDiretti.setObjectName("labelMotivazioneTecnicaScontriDiretti")
        self.frameCommentoFinale = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.frameCommentoFinale.setGeometry(QtCore.QRect(1170, 61, 641, 151))
        self.frameCommentoFinale.setStyleSheet("")
        self.frameCommentoFinale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCommentoFinale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCommentoFinale.setObjectName("frameCommentoFinale")
        self.labelCommentoFinale = QtWidgets.QLabel(self.frameCommentoFinale)
        self.labelCommentoFinale.setGeometry(QtCore.QRect(150, 0, 301, 21))
        self.labelCommentoFinale.setStyleSheet("\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelCommentoFinale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCommentoFinale.setObjectName("labelCommentoFinale")
        self.labelCommentoFinaleIndicatori = QtWidgets.QLabel(self.frameCommentoFinale)
        self.labelCommentoFinaleIndicatori.setGeometry(QtCore.QRect(20, 30, 620, 21))
        self.labelCommentoFinaleIndicatori.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelCommentoFinaleIndicatori.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCommentoFinaleIndicatori.setObjectName("labelCommentoFinaleIndicatori")
        self.labelCommentoFinaleConfidenza = QtWidgets.QLabel(self.frameCommentoFinale)
        self.labelCommentoFinaleConfidenza.setGeometry(QtCore.QRect(20, 50, 611, 21))
        self.labelCommentoFinaleConfidenza.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelCommentoFinaleConfidenza.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCommentoFinaleConfidenza.setObjectName("labelCommentoFinaleConfidenza")
        self.framePredizioni_8 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_8.setGeometry(QtCore.QRect(290, 330, 491, 121))
        self.framePredizioni_8.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.framePredizioni_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_8.setObjectName("framePredizioni_8")
        self.labelAnalisiSquadraDiCasa = QtWidgets.QLabel(self.framePredizioni_8)
        self.labelAnalisiSquadraDiCasa.setGeometry(QtCore.QRect(90, 0, 301, 21))
        self.labelAnalisiSquadraDiCasa.setStyleSheet("font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"background:transparent;\n"
"")
        self.labelAnalisiSquadraDiCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAnalisiSquadraDiCasa.setObjectName("labelAnalisiSquadraDiCasa")
        self.frameFormaRecente_5 = QtWidgets.QFrame(self.framePredizioni_8)
        self.frameFormaRecente_5.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_5.setObjectName("frameFormaRecente_5")
        self.labelFormaRecente_5 = QtWidgets.QLabel(self.frameFormaRecente_5)
        self.labelFormaRecente_5.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_5.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_5.setObjectName("labelFormaRecente_5")
        self.labelFormaRecenteSquadraDiCasa_5 = QtWidgets.QLabel(self.frameFormaRecente_5)
        self.labelFormaRecenteSquadraDiCasa_5.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_5.setObjectName("labelFormaRecenteSquadraDiCasa_5")
        self.labelFormaRecenteSquadraInTrasferta_5 = QtWidgets.QLabel(self.frameFormaRecente_5)
        self.labelFormaRecenteSquadraInTrasferta_5.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_5.setObjectName("labelFormaRecenteSquadraInTrasferta_5")
        self.labelAnalisiSqudraDiCasaInCasa = QtWidgets.QLabel(self.framePredizioni_8)
        self.labelAnalisiSqudraDiCasaInCasa.setGeometry(QtCore.QRect(20, 30, 460, 21))
        self.labelAnalisiSqudraDiCasaInCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
";")
        self.labelAnalisiSqudraDiCasaInCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSqudraDiCasaInCasa.setObjectName("labelAnalisiSqudraDiCasaInCasa")
        self.labelAnalisiSqudraDiCasaInTrasferta = QtWidgets.QLabel(self.framePredizioni_8)
        self.labelAnalisiSqudraDiCasaInTrasferta.setGeometry(QtCore.QRect(20, 50, 460, 21))
        self.labelAnalisiSqudraDiCasaInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelAnalisiSqudraDiCasaInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSqudraDiCasaInTrasferta.setObjectName("labelAnalisiSqudraDiCasaInTrasferta")
        self.labelAnalisiSqudraDiCasaGenerale = QtWidgets.QLabel(self.framePredizioni_8)
        self.labelAnalisiSqudraDiCasaGenerale.setGeometry(QtCore.QRect(20, 70, 460, 21))
        self.labelAnalisiSqudraDiCasaGenerale.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelAnalisiSqudraDiCasaGenerale.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSqudraDiCasaGenerale.setObjectName("labelAnalisiSqudraDiCasaGenerale")
        self.labelMediaPuntiCasa = QtWidgets.QLabel(self.framePredizioni_8)
        self.labelMediaPuntiCasa.setGeometry(QtCore.QRect(20, 90, 460, 21))
        self.labelMediaPuntiCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelMediaPuntiCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMediaPuntiCasa.setObjectName("labelMediaPuntiCasa")
        self.framePredizioni_9 = QtWidgets.QFrame(self.frameEsitiRanking_2)
        self.framePredizioni_9.setGeometry(QtCore.QRect(990, 330, 491, 121))
        self.framePredizioni_9.setStyleSheet("")
        self.framePredizioni_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePredizioni_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePredizioni_9.setObjectName("framePredizioni_9")
        self.labelAnalisiSquadraInTrasferta = QtWidgets.QLabel(self.framePredizioni_9)
        self.labelAnalisiSquadraInTrasferta.setGeometry(QtCore.QRect(90, 0, 301, 21))
        self.labelAnalisiSquadraInTrasferta.setStyleSheet("background:transparent;\n"
"font: 80 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelAnalisiSquadraInTrasferta.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAnalisiSquadraInTrasferta.setObjectName("labelAnalisiSquadraInTrasferta")
        self.frameFormaRecente_6 = QtWidgets.QFrame(self.framePredizioni_9)
        self.frameFormaRecente_6.setGeometry(QtCore.QRect(10, 400, 321, 91))
        self.frameFormaRecente_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormaRecente_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormaRecente_6.setObjectName("frameFormaRecente_6")
        self.labelFormaRecente_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecente_6.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.labelFormaRecente_6.setStyleSheet("\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(58, 255, 65);\n"
"")
        self.labelFormaRecente_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormaRecente_6.setObjectName("labelFormaRecente_6")
        self.labelFormaRecenteSquadraDiCasa_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecenteSquadraDiCasa_6.setGeometry(QtCore.QRect(10, 40, 301, 21))
        self.labelFormaRecenteSquadraDiCasa_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraDiCasa_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraDiCasa_6.setObjectName("labelFormaRecenteSquadraDiCasa_6")
        self.labelFormaRecenteSquadraInTrasferta_6 = QtWidgets.QLabel(self.frameFormaRecente_6)
        self.labelFormaRecenteSquadraInTrasferta_6.setGeometry(QtCore.QRect(10, 62, 301, 21))
        self.labelFormaRecenteSquadraInTrasferta_6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelFormaRecenteSquadraInTrasferta_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFormaRecenteSquadraInTrasferta_6.setObjectName("labelFormaRecenteSquadraInTrasferta_6")
        self.labelAnalisiSqudraInTrasfertaInCasa = QtWidgets.QLabel(self.framePredizioni_9)
        self.labelAnalisiSqudraInTrasfertaInCasa.setGeometry(QtCore.QRect(20, 30, 460, 21))
        self.labelAnalisiSqudraInTrasfertaInCasa.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelAnalisiSqudraInTrasfertaInCasa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSqudraInTrasfertaInCasa.setObjectName("labelAnalisiSqudraInTrasfertaInCasa")
        self.labelAnalisiSqudraInTrasfertaInTrasferta = QtWidgets.QLabel(self.framePredizioni_9)
        self.labelAnalisiSqudraInTrasfertaInTrasferta.setGeometry(QtCore.QRect(20, 50, 460, 21))
        self.labelAnalisiSqudraInTrasfertaInTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelAnalisiSqudraInTrasfertaInTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSqudraInTrasfertaInTrasferta.setObjectName("labelAnalisiSqudraInTrasfertaInTrasferta")
        self.labelAnalisiSquadraInTrasfertaGenerale = QtWidgets.QLabel(self.framePredizioni_9)
        self.labelAnalisiSquadraInTrasfertaGenerale.setGeometry(QtCore.QRect(20, 70, 460, 21))
        self.labelAnalisiSquadraInTrasfertaGenerale.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"")
        self.labelAnalisiSquadraInTrasfertaGenerale.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAnalisiSquadraInTrasfertaGenerale.setObjectName("labelAnalisiSquadraInTrasfertaGenerale")
        self.labelMediaPuntiTrasferta = QtWidgets.QLabel(self.framePredizioni_9)
        self.labelMediaPuntiTrasferta.setGeometry(QtCore.QRect(20, 90, 460, 21))
        self.labelMediaPuntiTrasferta.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: white;\n"
"background:transparent;")
        self.labelMediaPuntiTrasferta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMediaPuntiTrasferta.setObjectName("labelMediaPuntiTrasferta")
        self.frameGrafico = QtWidgets.QFrame(self.FramePrincipale)
        self.frameGrafico.setGeometry(QtCore.QRect(210, 1110, 1400, 711))
        self.frameGrafico.setStyleSheet("background:Transparent")
        self.frameGrafico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGrafico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGrafico.setObjectName("frameGrafico")
        self.labelGrafico = QtWidgets.QLabel(self.frameGrafico)
        self.labelGrafico.setGeometry(QtCore.QRect(10, 70, 1381, 641))
        self.labelGrafico.setText("")
        self.labelGrafico.setPixmap(QtGui.QPixmap("UI\\../confronto_squadre.png"))
        self.labelGrafico.setScaledContents(True)
        self.labelGrafico.setWordWrap(False)
        self.labelGrafico.setObjectName("labelGrafico")
        self.frameButton = QtWidgets.QFrame(self.FramePrincipale)
        self.frameButton.setGeometry(QtCore.QRect(230, 600, 1861, 78))
        self.frameButton.setStyleSheet("background-color: Transparent;\n"
"")
        self.frameButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButton.setObjectName("frameButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frameButton)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1401, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonPredizione = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonPredizione.setStyleSheet("QPushButton {\n"
"font: 14pt \"Segoe UI\";\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));\n"
"}")
        self.buttonPredizione.setObjectName("buttonPredizione")
        self.horizontalLayout_2.addWidget(self.buttonPredizione)
        self.buttonReset = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonReset.setStyleSheet("QPushButton {\n"
"font: 14pt \"Segoe UI\";\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));\n"
"}")
        self.buttonReset.setObjectName("buttonReset")
        self.horizontalLayout_2.addWidget(self.buttonReset)
        self.buttonEsci = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonEsci.setStyleSheet("QPushButton {\n"
"font: 14pt \"Segoe UI\";\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));\n"
"}")
        self.buttonEsci.setObjectName("buttonEsci")
        self.horizontalLayout_2.addWidget(self.buttonEsci)
        self.VerticalLayOut.addWidget(self.FramePrincipale)
        self.scrollAreaRanking.setWidget(self.scrollAreaWidgetEsitiRanking)
        self.frameTestataPrincipale = QtWidgets.QFrame(self.centralwidget)
        self.frameTestataPrincipale.setGeometry(QtCore.QRect(10, 10, 1900, 80))
        self.frameTestataPrincipale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTestataPrincipale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTestataPrincipale.setObjectName("frameTestataPrincipale")
        self.labelTestataPrincipale = QtWidgets.QLabel(self.frameTestataPrincipale)
        self.labelTestataPrincipale.setGeometry(QtCore.QRect(475, 10, 950, 61))
        self.labelTestataPrincipale.setStyleSheet("color: rgb(58, 255, 65);\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"")
        self.labelTestataPrincipale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestataPrincipale.setObjectName("labelTestataPrincipale")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 1861, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxCasa = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxCasa.setStyleSheet("QComboBox {\n"
"    background-color: #1e293b;\n"
"    color: #ffffff;\n"
"    border: 2px solid #3b82f6;\n"
"    border-radius: 6px;\n"
"    padding: 4px 10px;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"}\n"
"QComboBox:hover {\n"
"    border: 2px solid #60a5fa;\n"
"    background-color: #273549;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e293b;\n"
"    color: #ffffff;\n"
"    selection-background-color: #3b82f6;\n"
"    selection-color: #ffffff;\n"
"    border: 1px solid #4b5563;\n"
"    padding: 4px;\n"
"}")
        self.comboBoxCasa.setObjectName("comboBoxCasa")
        self.horizontalLayout.addWidget(self.comboBoxCasa)
        self.comboBoxTrasferta = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxTrasferta.setStyleSheet("QComboBox {\n"
"    background-color: #1e293b;\n"
"    color: #ffffff;\n"
"    border: 2px solid #3b82f6;\n"
"    border-radius: 6px;\n"
"    padding: 4px 10px;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"}\n"
"QComboBox:hover {\n"
"    border: 2px solid #60a5fa;\n"
"    background-color: #273549;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e293b;\n"
"    color: #ffffff;\n"
"    selection-background-color: #3b82f6;\n"
"    selection-color: #ffffff;\n"
"    border: 1px solid #4b5563;\n"
"    padding: 4px;\n"
"}")
        self.comboBoxTrasferta.setObjectName("comboBoxTrasferta")
        self.horizontalLayout.addWidget(self.comboBoxTrasferta)
        self.framePartita = QtWidgets.QFrame(self.centralwidget)
        self.framePartita.setGeometry(QtCore.QRect(10, 130, 1861, 71))
        self.framePartita.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(14, 0, 255, 255), stop:1 rgba(76, 152, 228, 255));")
        self.framePartita.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePartita.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePartita.setObjectName("framePartita")
        self.labelSquadraDiCasa = QtWidgets.QLabel(self.framePartita)
        self.labelSquadraDiCasa.setGeometry(QtCore.QRect(30, 10, 550, 50))
        self.labelSquadraDiCasa.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"")
        self.labelSquadraDiCasa.setObjectName("labelSquadraDiCasa")
        self.labelScudettoSquadraDiCasa = QtWidgets.QLabel(self.framePartita)
        self.labelScudettoSquadraDiCasa.setGeometry(QtCore.QRect(610, -1, 70, 70))
        self.labelScudettoSquadraDiCasa.setStyleSheet("color: white;\n"
"font: 8pt \"Segoe UI\";")
        self.labelScudettoSquadraDiCasa.setObjectName("labelScudettoSquadraDiCasa")
        self.labelSquadraInTrasferta = QtWidgets.QLabel(self.framePartita)
        self.labelSquadraInTrasferta.setGeometry(QtCore.QRect(970, 10, 550, 50))
        self.labelSquadraInTrasferta.setStyleSheet("color: white;\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"background: transparent;")
        self.labelSquadraInTrasferta.setObjectName("labelSquadraInTrasferta")
        self.labelScudettoSquadraInTrasferta = QtWidgets.QLabel(self.framePartita)
        self.labelScudettoSquadraInTrasferta.setGeometry(QtCore.QRect(1550, -1, 70, 70))
        self.labelScudettoSquadraInTrasferta.setStyleSheet("color: white;\n"
"font: 8pt \"Segoe UI\";")
        self.labelScudettoSquadraInTrasferta.setObjectName("labelScudettoSquadraInTrasferta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTestataEsitiDalRanking.setText(_translate("MainWindow", "=== Esiti Dal Ranking ==="))
        self.labelPredizioni.setText(_translate("MainWindow", "PREDIZIONI"))
        self.labelFormaRecente.setText(_translate("MainWindow", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa.setText(_translate("MainWindow", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 1.6/3.0 punti/partita"))
        self.labelUnderOver.setText(_translate("MainWindow", "--- UNDER/OVER ---"))
        self.labelUnder15.setText(_translate("MainWindow", "Under 1.5: 43%"))
        self.labelOver15.setText(_translate("MainWindow", "Over 1.5: 57%"))
        self.labelUnder25.setText(_translate("MainWindow", "Under 2.5: 60%"))
        self.labelOver25.setText(_translate("MainWindow", "Over 2.5: 40%"))
        self.labelProbabilitaEsito.setText(_translate("MainWindow", "--- Probabilità Esito ---"))
        self.labelProbabilitaVittoria.setText(_translate("MainWindow", "1 (Vittoria Roma): 85%"))
        self.labelProbabilitaPareggio.setText(_translate("MainWindow", "X (Pareggio): 10%"))
        self.labelProbabilitaSconfitta.setText(_translate("MainWindow", "2 (Vittoria Udinese): 15%"))
        self.labelPredizioneGoal.setText(_translate("MainWindow", "--- Predizione goals ---"))
        self.labelGoalPrevisti.setText(_translate("MainWindow", "Goal previsti: Hellas Verona 1.0 - 1.3 Cremonese"))
        self.labelEsitoPrevisto.setText(_translate("MainWindow", "Esito Previsto: 1"))
        self.labelDoppiaChanceSuggerita.setText(_translate("MainWindow", "Doppia chance suggerita: 1X"))
        self.labelPredizioni_2.setText(_translate("MainWindow", "Ranking Campionati Precedenti"))
        self.labelStatisticheStoricheAggregate.setText(_translate("MainWindow", "📈 --- Statistiche storiche Aggegate ---"))
        self.labelStatisticheStoricheAggregateSquadraDiCasa.setText(_translate("MainWindow", "Roma: 228 partite, 113-51-64, 375-271"))
        self.labelStatisticheStoricheAggregateSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 228 partite, 62-73-93, 265-324"))
        self.labelRankingCampionatiPrecedentiInTraferta.setText(_translate("MainWindow", "✈️ --- In Trasferta ---"))
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraDiCasa.setText(_translate("MainWindow", "Roma: 7° posto"))
        self.labelRankingCampionatiPrecedentiInTrafertaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 10° posto"))
        self.labelRankingCampionatiPrecedentiInCasa.setText(_translate("MainWindow", "🏠 --- In Casa ---"))
        self.labelRankingCampionatiPrecedentiInCasaSquadraDiCasa.setText(_translate("MainWindow", "Roma: 3° posto"))
        self.labelRankingCampionatiPrecedentiInCasaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 12° posto%"))
        self.labelRankingCampionatiPrecedentiGenerale.setText(_translate("MainWindow", "📊 --- Generale ---"))
        self.labelRankingCampionatiPrecedentiGeneraleSquadraDiCasa.setText(_translate("MainWindow", "Roma 7° posto"))
        self.labelRankingCampionatiPrecedentiGeneraleSquadraInTrasferta.setText(_translate("MainWindow", "Udinese 11° posto"))
        self.labelRankingCampionatoAttuale.setText(_translate("MainWindow", "Ranking Campionato Attuale"))
        self.labelRankingCampionatoAttualeInTrasferta.setText(_translate("MainWindow", "✈️ --- In Trasferta ---"))
        self.labelRankingCampionatoAttualeInTrasfertaSquadraDiCasa.setText(_translate("MainWindow", "Roma: 1° posto"))
        self.labelRankingCampionatoAttualeInTrasfertaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 9° posto"))
        self.labelRankingCampionatoAttualeInCasa.setText(_translate("MainWindow", "🏠 --- In Casa ---"))
        self.labelRankingCampionatoAttualeInCasaSquadraDiCasa.setText(_translate("MainWindow", "Roma: 8° posto"))
        self.labelRankingCampionatoAttualeInCasaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 9° posto"))
        self.labelRankingCampionatoAttualeGenerale.setText(_translate("MainWindow", "📊 --- Generale ---"))
        self.labelRankingCampionatoAttualeGeneraleSquadraDiCasa.setText(_translate("MainWindow", "Roma: 4° posto"))
        self.labelRankingCampionatoAttualeGeneraleSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 9° posto"))
        self.labelRankingUltime5Partite.setText(_translate("MainWindow", "Ranking Ultime 5 Partite"))
        self.labelRankingUltime5PartiteInTrasferta.setText(_translate("MainWindow", "✈️ --- In Trasferta ---"))
        self.labelRankingUltime5PartiteInTrasfertaSquadraDiCasa.setText(_translate("MainWindow", "Roma: 1° posto"))
        self.labelRankingUltime5PartiteInTrasfertaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 10° posto"))
        self.labelRankingUltime5PartiteInCasa.setText(_translate("MainWindow", "🏠 --- In Casa ---"))
        self.labelRankingUltime5PartiteInCasaSquadraDiCara.setText(_translate("MainWindow", "Roma: 8° posto"))
        self.labelRankingUltime5PartiteInCasaSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 10° posto"))
        self.labelRankingUltime5PartiteGenerale.setText(_translate("MainWindow", "📊 --- Generale ---"))
        self.labelRankingUltime5PartiteGeneraleSqaudraDiCasa.setText(_translate("MainWindow", "Roma: 6° posto"))
        self.labelRankingUltime5PartiteGeneraleSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 9° posto"))
        self.labelScontriStoriciDiretti.setText(_translate("MainWindow", "=== SCONTRI DIRETTI STORICI ==="))
        self.labelScontriTrovati.setText(_translate("MainWindow", "Trovati 12 scontri diretti storici"))
        self.labelUltime5PartiteTraLe2Squadre.setText(_translate("MainWindow", "📅 ULTIME 5 PARTITE TRA LE DUE SQUADRE"))
        self.labelUltime5PartiteTraLe2Squadre_3.setText(_translate("MainWindow", "25/Apr: Udinese 1-2 Roma"))
        self.labelUltime5PartiteTraLe2Squadre_5.setText(_translate("MainWindow", "26/Gen: Udinese 1-2 Roma"))
        self.labelUltime5PartiteTraLe2Squadre_4.setText(_translate("MainWindow", "22/Set: Roma 3-0 Udinese"))
        self.labelUltime5PartiteTraLe2Squadre_2.setText(_translate("MainWindow", "26/Nov: Roma 3-1 Udinese"))
        self.labelUltime5PartiteTraLe2Squadre_1.setText(_translate("MainWindow", "16/Apr: Roma 3-0 Udinese"))
        self.labelBilancioScontriDirettiPareggi.setText(_translate("MainWindow", "Pareggi: 1"))
        self.labelBilancioScontriDiretti.setText(_translate("MainWindow", "🏆 BILANCIO SCONTRI DIRETTI:"))
        self.labelBilancioScontriDirettiSquadraDiCasa.setText(_translate("MainWindow", "Roma: 9 vittorie"))
        self.labelBilancioScontriDirettiSquadraInTrasferta.setText(_translate("MainWindow", "Udinese: 2 vittorie"))
        self.labelTestataEsitiDalRanking_2.setText(_translate("MainWindow", "=== Analisi e Raccomandazioni ==="))
        self.labelScommessaConsigliata.setText(_translate("MainWindow", "**🎯 SCOMMESSA CONSIGLIATA**"))
        self.labelScommessaConsigliataDoppiaChance.setText(_translate("MainWindow", "Doppia Chance 1X (Casa o Pareggio)"))
        self.labelScommessaConsigliataProbabilitaSuccesso.setText(_translate("MainWindow", "Probabilità di successo: 95%"))
        self.labelScommessaConsigliataLivelloRischio.setText(_translate("MainWindow", "Livello rischio: 🟢 BASSO"))
        self.labelframeAltreOpzioni.setText(_translate("MainWindow", "**📊ALTRE OPZIONI INTERESSANTI:**"))
        self.labelAltreOpzioniSuggerimenti.setText(_translate("MainWindow", "Combo suggerita: 1 + Under 2.5"))
        self.labelMotivazioneTecnica.setText(_translate("MainWindow", "🧠 **MOTIVAZIONE TECNICA:**"))
        self.labelMotivazioneTecnicaPredizione.setText(_translate("MainWindow", "📊 Predizione esito: Roma favorito con 85% di probabilità"))
        self.labelMotivazioneTecnicaGoalsPrevisti.setText(_translate("MainWindow", "⚽ Goal previsti: Roma vs Udinese → 2.1 goal totali"))
        self.labelMotivazioneTecnicaFormaRecente.setText(_translate("MainWindow", "🔥 Forma recente: Roma in forma migliore (1.8 vs 1.4)"))
        self.labelMotivazioneTecnicaRankingAttuale.setText(_translate("MainWindow", "🏆 Ranking attuale: Roma meglio classificato (2° vs 10°)"))
        self.labelMotivazioneTecnicaScontriDiretti.setText(_translate("MainWindow", "⚔️  Scontri diretti: Roma dominante (9-2-1)"))
        self.labelCommentoFinale.setText(_translate("MainWindow", "💡 **COMMENTO FINALE AI:**"))
        self.labelCommentoFinaleIndicatori.setText(_translate("MainWindow", "Indicatori contrastanti. La scommessa consigliata è la più prudente."))
        self.labelCommentoFinaleConfidenza.setText(_translate("MainWindow", "🟢 **Confidenza ALTA** - Scommessa consigliata con ottime probabilità di successo."))
        self.labelAnalisiSquadraDiCasa.setText(_translate("MainWindow", "Roma - Analisi forma:"))
        self.labelFormaRecente_5.setText(_translate("MainWindow", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_5.setText(_translate("MainWindow", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_5.setText(_translate("MainWindow", "Udinese: 1.6/3.0 punti/partita"))
        self.labelAnalisiSqudraDiCasaInCasa.setText(_translate("MainWindow", "🏠 In CASA (ultime 5): 2 1 2 1 1"))
        self.labelAnalisiSqudraDiCasaInTrasferta.setText(_translate("MainWindow", "✈️  In TRASFERTA (ultime 5): 1 1 1 1 2"))
        self.labelAnalisiSqudraDiCasaGenerale.setText(_translate("MainWindow", "📊 GENERALE (ultime 5): 2 1 1 2 1  ← Usati per calcolo forma"))
        self.labelMediaPuntiCasa.setText(_translate("MainWindow", "💪 Media punti/partita: 1.80/3.0"))
        self.labelAnalisiSquadraInTrasferta.setText(_translate("MainWindow", "Udinese - Analisi forma:"))
        self.labelFormaRecente_6.setText(_translate("MainWindow", "--- FORMA RECENTE (ultime 5 partite) ---"))
        self.labelFormaRecenteSquadraDiCasa_6.setText(_translate("MainWindow", "Roma: 1.8/3.0 punti/partita"))
        self.labelFormaRecenteSquadraInTrasferta_6.setText(_translate("MainWindow", "Udinese: 1.6/3.0 punti/partita"))
        self.labelAnalisiSqudraInTrasfertaInCasa.setText(_translate("MainWindow", "🏠 In CASA (ultime 5): 2 1 2 1 1"))
        self.labelAnalisiSqudraInTrasfertaInTrasferta.setText(_translate("MainWindow", "✈️  In TRASFERTA (ultime 5): 1 1 1 1 2"))
        self.labelAnalisiSquadraInTrasfertaGenerale.setText(_translate("MainWindow", "📊 GENERALE (ultime 5): 2 1 1 2 1  ← Usati per calcolo forma"))
        self.labelMediaPuntiTrasferta.setText(_translate("MainWindow", "💪 Media punti/partita: 1.80/3.0"))
        self.buttonPredizione.setToolTip(_translate("MainWindow", "Clicca per creare la predizione dopo aver inserito le squadre"))
        self.buttonPredizione.setText(_translate("MainWindow", "Predizione"))
        self.buttonReset.setToolTip(_translate("MainWindow", "Cancella i valori inseriti"))
        self.buttonReset.setText(_translate("MainWindow", "Reset"))
        self.buttonEsci.setToolTip(_translate("MainWindow", "Esci"))
        self.buttonEsci.setText(_translate("MainWindow", "Esci"))
        self.labelTestataPrincipale.setText(_translate("MainWindow", "=== ANALISI PARTITA ==="))
        self.comboBoxCasa.setToolTip(_translate("MainWindow", "Inserire la squadra di casa per predire il match"))
        self.comboBoxTrasferta.setToolTip(_translate("MainWindow", "Inserire la squadra in trasferta per predire il match"))
        self.labelSquadraDiCasa.setText(_translate("MainWindow", "Sqaudra di casa"))
        self.labelScudettoSquadraDiCasa.setText(_translate("MainWindow", "scudeto"))
        self.labelSquadraInTrasferta.setText(_translate("MainWindow", "Sqaudra in trasferta"))
        self.labelScudettoSquadraInTrasferta.setText(_translate("MainWindow", "Scudetto"))
